// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package criblcontrolplanesdkgo

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/config"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/hooks"
)

type Versions struct {
	Branches *Branches
	Commits  *Commits
	Configs  *VersionsConfigs
	Statuses *VersionsStatuses

	rootSDK          *CriblControlPlane
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newVersions(rootSDK *CriblControlPlane, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Versions {
	return &Versions{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		Branches:         newBranches(rootSDK, sdkConfig, hooks),
		Commits:          newCommits(rootSDK, sdkConfig, hooks),
		Configs:          newVersionsConfigs(rootSDK, sdkConfig, hooks),
		Statuses:         newVersionsStatuses(rootSDK, sdkConfig, hooks),
	}
}
