// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-control-plane-sdk-go/models/components"
)

type DeleteOutputSystemPqByPackAndIDRequest struct {
	// The <code>id</code> of the Destination to clear the PQ for.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The <code>id</code> of the Pack to clear.
	Pack string `pathParam:"style=simple,explode=false,name=pack"`
}

func (d *DeleteOutputSystemPqByPackAndIDRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteOutputSystemPqByPackAndIDRequest) GetPack() string {
	if d == nil {
		return ""
	}
	return d.Pack
}

type DeleteOutputSystemPqByPackAndIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of job ids for the background job that clears the persistent queue
	CountedString *components.CountedString
}

func (d *DeleteOutputSystemPqByPackAndIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteOutputSystemPqByPackAndIDResponse) GetCountedString() *components.CountedString {
	if d == nil {
		return nil
	}
	return d.CountedString
}
