// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
	"github.com/criblio/cribl-control-plane-sdk-go/models/components"
)

type GetInputPqByIDRequest struct {
	// The <code>id</code> of the Source to get PQ job information for.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetInputPqByIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetInputPqByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// information about the latest job to clear the PQ for the Source
	CountedJobInfo *components.CountedJobInfo
}

func (g GetInputPqByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInputPqByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetInputPqByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInputPqByIDResponse) GetCountedJobInfo() *components.CountedJobInfo {
	if g == nil {
		return nil
	}
	return g.CountedJobInfo
}
