// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-control-plane-sdk-go/models/components"
)

type GetInputStatusRequest struct {
	// Set to true <code>true</code> to include metrics for each Source. Otherwise, <code>false</code> (default).
	Metrics *bool `queryParam:"style=form,explode=true,name=metrics"`
	// Set to <code>true</code> to prefix the Source <code>id</code> with the Source type. Otherwise, <code>false</code> (default).
	Type *bool `queryParam:"style=form,explode=true,name=type"`
}

func (g *GetInputStatusRequest) GetMetrics() *bool {
	if g == nil {
		return nil
	}
	return g.Metrics
}

func (g *GetInputStatusRequest) GetType() *bool {
	if g == nil {
		return nil
	}
	return g.Type
}

type GetInputStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of InputStatus objects
	CountedInputStatus *components.CountedInputStatus
}

func (g *GetInputStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInputStatusResponse) GetCountedInputStatus() *components.CountedInputStatus {
	if g == nil {
		return nil
	}
	return g.CountedInputStatus
}
