// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
	"github.com/criblio/cribl-control-plane-sdk-go/models/components"
)

type GetOutputStatusRequest struct {
	// Set to <code>true</code> to include metrics for each Destination. Otherwise, <code>false</code> (default).
	Metrics *bool `queryParam:"style=form,explode=true,name=metrics"`
	// Set to <code>true</code> to prefix the Destination <code>id</code> with the Destination type. Otherwise, <code>false</code> (default).
	Type *bool `queryParam:"style=form,explode=true,name=type"`
	// Starting point from which to retrieve results for this request. Use with <code>limit</code> to paginate the response into manageable batches.
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// Maximum number of items to return in the response for this request. Use with <code>offset</code> to paginate the response into manageable batches.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
}

func (g *GetOutputStatusRequest) GetMetrics() *bool {
	if g == nil {
		return nil
	}
	return g.Metrics
}

func (g *GetOutputStatusRequest) GetType() *bool {
	if g == nil {
		return nil
	}
	return g.Type
}

func (g *GetOutputStatusRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetOutputStatusRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

type GetOutputStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Destination status objects
	CountedOutputStatus *components.CountedOutputStatus

	Next func() (*GetOutputStatusResponse, error)
}

func (g GetOutputStatusResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOutputStatusResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetOutputStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOutputStatusResponse) GetCountedOutputStatus() *components.CountedOutputStatus {
	if g == nil {
		return nil
	}
	return g.CountedOutputStatus
}
