// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-control-plane-sdk-go/models/components"
)

type UpdatePipelineByIDRequest struct {
	// The <code>id</code> of the Pipeline to update.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Pipeline object
	Pipeline components.Pipeline `request:"mediaType=application/json"`
}

func (u *UpdatePipelineByIDRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePipelineByIDRequest) GetPipeline() components.Pipeline {
	if u == nil {
		return components.Pipeline{}
	}
	return u.Pipeline
}

// UpdatePipelineByIDResponseBody - a list of Pipeline objects
type UpdatePipelineByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                `json:"count,omitempty"`
	Items []components.Pipeline `json:"items,omitempty"`
}

func (u *UpdatePipelineByIDResponseBody) GetCount() *int64 {
	if u == nil {
		return nil
	}
	return u.Count
}

func (u *UpdatePipelineByIDResponseBody) GetItems() []components.Pipeline {
	if u == nil {
		return nil
	}
	return u.Items
}

type UpdatePipelineByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Pipeline objects
	Object *UpdatePipelineByIDResponseBody
}

func (u *UpdatePipelineByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePipelineByIDResponse) GetObject() *UpdatePipelineByIDResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
