// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type AddHecTokenRequest struct {
	AllowedIndexesAtToken []string                 `json:"allowedIndexesAtToken,omitzero"`
	Description           *string                  `json:"description,omitzero"`
	Enabled               *bool                    `json:"enabled,omitzero"`
	Metadata              []EventBreakerRuleFields `json:"metadata,omitzero"`
	Token                 string                   `json:"token"`
}

func (a AddHecTokenRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddHecTokenRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddHecTokenRequest) GetAllowedIndexesAtToken() []string {
	if a == nil {
		return nil
	}
	return a.AllowedIndexesAtToken
}

func (a *AddHecTokenRequest) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AddHecTokenRequest) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *AddHecTokenRequest) GetMetadata() []EventBreakerRuleFields {
	if a == nil {
		return nil
	}
	return a.Metadata
}

func (a *AddHecTokenRequest) GetToken() string {
	if a == nil {
		return ""
	}
	return a.Token
}
