// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuthenticationTypeOptionsLokiAuth - Loki logs authentication type
type AuthenticationTypeOptionsLokiAuth string

const (
	AuthenticationTypeOptionsLokiAuthNone              AuthenticationTypeOptionsLokiAuth = "none"
	AuthenticationTypeOptionsLokiAuthBasic             AuthenticationTypeOptionsLokiAuth = "basic"
	AuthenticationTypeOptionsLokiAuthCredentialsSecret AuthenticationTypeOptionsLokiAuth = "credentialsSecret"
	AuthenticationTypeOptionsLokiAuthToken             AuthenticationTypeOptionsLokiAuth = "token"
	AuthenticationTypeOptionsLokiAuthTextSecret        AuthenticationTypeOptionsLokiAuth = "textSecret"
	AuthenticationTypeOptionsLokiAuthOauth             AuthenticationTypeOptionsLokiAuth = "oauth"
)

func (e AuthenticationTypeOptionsLokiAuth) ToPointer() *AuthenticationTypeOptionsLokiAuth {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AuthenticationTypeOptionsLokiAuth) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "basic", "credentialsSecret", "token", "textSecret", "oauth":
			return true
		}
	}
	return false
}
