// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

// CollectorSplunkAuthentication4 - Authentication method for Discover and Collect REST calls
type CollectorSplunkAuthentication4 string

const (
	// CollectorSplunkAuthentication4None None
	CollectorSplunkAuthentication4None CollectorSplunkAuthentication4 = "none"
	// CollectorSplunkAuthentication4Basic Basic
	CollectorSplunkAuthentication4Basic CollectorSplunkAuthentication4 = "basic"
	// CollectorSplunkAuthentication4BasicSecret Basic (credentials secret)
	CollectorSplunkAuthentication4BasicSecret CollectorSplunkAuthentication4 = "basicSecret"
	// CollectorSplunkAuthentication4Token Bearer Token
	CollectorSplunkAuthentication4Token CollectorSplunkAuthentication4 = "token"
	// CollectorSplunkAuthentication4TokenSecret Bearer Token (text secret)
	CollectorSplunkAuthentication4TokenSecret CollectorSplunkAuthentication4 = "tokenSecret"
)

func (e CollectorSplunkAuthentication4) ToPointer() *CollectorSplunkAuthentication4 {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CollectorSplunkAuthentication4) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "basic", "basicSecret", "token", "tokenSecret":
			return true
		}
	}
	return false
}

// CollectorSplunkType5 - Collector type: splunk
type CollectorSplunkType5 string

const (
	CollectorSplunkType5Splunk CollectorSplunkType5 = "splunk"
)

func (e CollectorSplunkType5) ToPointer() *CollectorSplunkType5 {
	return &e
}
func (e *CollectorSplunkType5) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "splunk":
		*e = CollectorSplunkType5(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CollectorSplunkType5: %v", v)
	}
}

type CollectRequestParam4 struct {
	Name string `json:"name"`
	// JavaScript expression to compute the parameter's value, normally enclosed in backticks (`${earliest}`). If a constant, use single quotes ('earliest'). Values without delimiters (earliest) are evaluated as strings.
	Value string `json:"value"`
}

func (c CollectRequestParam4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectRequestParam4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectRequestParam4) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CollectRequestParam4) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

type CollectorSplunkCollectRequestHeader4 struct {
	Name string `json:"name"`
	// JavaScript expression to compute the header's value, normally enclosed in backticks (`${earliest}`). If a constant, use single quotes ('earliest'). Values without delimiters (earliest) are evaluated as strings.
	Value string `json:"value"`
}

func (c CollectorSplunkCollectRequestHeader4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkCollectRequestHeader4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkCollectRequestHeader4) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CollectorSplunkCollectRequestHeader4) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

type CollectorSplunkRetryRules4 struct {
	// The algorithm to use when performing HTTP retries
	Type                *RetryTypeOptionsRetryRules `default:"backoff" json:"type"`
	Interval            any                         `json:"interval,omitempty"`
	Limit               any                         `json:"limit,omitempty"`
	Multiplier          any                         `json:"multiplier,omitempty"`
	Codes               any                         `json:"codes,omitempty"`
	EnableHeader        any                         `json:"enableHeader,omitempty"`
	RetryConnectTimeout any                         `json:"retryConnectTimeout,omitempty"`
	RetryConnectReset   any                         `json:"retryConnectReset,omitempty"`
}

func (c CollectorSplunkRetryRules4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkRetryRules4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkRetryRules4) GetType() *RetryTypeOptionsRetryRules {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CollectorSplunkRetryRules4) GetInterval() any {
	if c == nil {
		return nil
	}
	return c.Interval
}

func (c *CollectorSplunkRetryRules4) GetLimit() any {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *CollectorSplunkRetryRules4) GetMultiplier() any {
	if c == nil {
		return nil
	}
	return c.Multiplier
}

func (c *CollectorSplunkRetryRules4) GetCodes() any {
	if c == nil {
		return nil
	}
	return c.Codes
}

func (c *CollectorSplunkRetryRules4) GetEnableHeader() any {
	if c == nil {
		return nil
	}
	return c.EnableHeader
}

func (c *CollectorSplunkRetryRules4) GetRetryConnectTimeout() any {
	if c == nil {
		return nil
	}
	return c.RetryConnectTimeout
}

func (c *CollectorSplunkRetryRules4) GetRetryConnectReset() any {
	if c == nil {
		return nil
	}
	return c.RetryConnectReset
}

type CollectorSplunkSplunk4 struct {
	// Authentication method for Discover and Collect REST calls
	Authentication *CollectorSplunkAuthentication4 `default:"basic" json:"authentication"`
	// URL to use for login API call, this call is expected to be a POST.
	LoginURL *string `default:"https://localhost:9000/api/v1/auth/login" json:"loginUrl"`
	// Select or create a stored secret that references your login credentials
	CredentialsSecret string `json:"credentialsSecret"`
	// Template for POST body to send with login request, ${username} and ${password} are used to specify location of these attributes in the message
	LoginBody *string `default:"{ \"username\": \"\\${username}\", \"password\": \"\\${password}\" }" json:"loginBody"`
	// Path to token attribute in login response body. Nested attributes are allowed.
	TokenRespAttribute *string `default:"token" json:"tokenRespAttribute"`
	// JavaScript expression to compute the Authorization header to pass in discover and collect calls. The value ${token} is used to reference the token obtained from login.
	AuthHeaderExpr *string `default:"Bearer \\${token}" json:"authHeaderExpr"`
	// Collector type: splunk
	Type CollectorSplunkType5 `json:"type"`
	// Search head base URL. Can be an expression. Default is https://localhost:8089.
	SearchHead *string `default:"https://localhost:8089" json:"searchHead"`
	// Examples: 'index=myAppLogs level=error channel=myApp' OR '| mstats avg(myStat) as myStat WHERE index=myStatsIndex.'
	Search string `json:"search"`
	// The earliest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-16m@m'
	Earliest *string `json:"earliest,omitempty"`
	// The latest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-1m@m'
	Latest *string `json:"latest,omitempty"`
	// REST API used to create a search
	Endpoint *string `default:"/services/search/v2/jobs/export" json:"endpoint"`
	// Format of the returned output
	OutputMode *OutputModeOptions `default:"json" json:"outputMode"`
	// Optional collect request parameters
	CollectRequestParams []CollectRequestParam4 `json:"collectRequestParams,omitempty"`
	// Optional collect request headers
	CollectRequestHeaders []CollectorSplunkCollectRequestHeader4 `json:"collectRequestHeaders,omitempty"`
	// HTTP request inactivity timeout. Use 0 for no timeout.
	Timeout *float64 `default:"0" json:"timeout"`
	// Use round-robin DNS lookup. Suitable when DNS server returns multiple addresses in sort order.
	UseRoundRobinDNS *bool `default:"false" json:"useRoundRobinDns"`
	// Disable collector event time filtering when a date range is specified
	DisableTimeFilter *bool `default:"true" json:"disableTimeFilter"`
	// Reject certificates that cannot be verified against a valid CA (such as self-signed certificates)
	RejectUnauthorized *bool `default:"false" json:"rejectUnauthorized"`
	// Escape characters (\") in search queries will be passed directly to Splunk
	HandleEscapedChars *bool                       `default:"false" json:"handleEscapedChars"`
	RetryRules         *CollectorSplunkRetryRules4 `json:"retryRules,omitempty"`
	Username           *string                     `json:"username,omitempty"`
	Password           *string                     `json:"password,omitempty"`
	Token              *string                     `json:"token,omitempty"`
	// Select or create a stored secret that references your Bearer token
	TokenSecret *string `json:"tokenSecret,omitempty"`
}

func (c CollectorSplunkSplunk4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkSplunk4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"credentialsSecret", "type", "search"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkSplunk4) GetAuthentication() *CollectorSplunkAuthentication4 {
	if c == nil {
		return nil
	}
	return c.Authentication
}

func (c *CollectorSplunkSplunk4) GetLoginURL() *string {
	if c == nil {
		return nil
	}
	return c.LoginURL
}

func (c *CollectorSplunkSplunk4) GetCredentialsSecret() string {
	if c == nil {
		return ""
	}
	return c.CredentialsSecret
}

func (c *CollectorSplunkSplunk4) GetLoginBody() *string {
	if c == nil {
		return nil
	}
	return c.LoginBody
}

func (c *CollectorSplunkSplunk4) GetTokenRespAttribute() *string {
	if c == nil {
		return nil
	}
	return c.TokenRespAttribute
}

func (c *CollectorSplunkSplunk4) GetAuthHeaderExpr() *string {
	if c == nil {
		return nil
	}
	return c.AuthHeaderExpr
}

func (c *CollectorSplunkSplunk4) GetType() CollectorSplunkType5 {
	if c == nil {
		return CollectorSplunkType5("")
	}
	return c.Type
}

func (c *CollectorSplunkSplunk4) GetSearchHead() *string {
	if c == nil {
		return nil
	}
	return c.SearchHead
}

func (c *CollectorSplunkSplunk4) GetSearch() string {
	if c == nil {
		return ""
	}
	return c.Search
}

func (c *CollectorSplunkSplunk4) GetEarliest() *string {
	if c == nil {
		return nil
	}
	return c.Earliest
}

func (c *CollectorSplunkSplunk4) GetLatest() *string {
	if c == nil {
		return nil
	}
	return c.Latest
}

func (c *CollectorSplunkSplunk4) GetEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.Endpoint
}

func (c *CollectorSplunkSplunk4) GetOutputMode() *OutputModeOptions {
	if c == nil {
		return nil
	}
	return c.OutputMode
}

func (c *CollectorSplunkSplunk4) GetCollectRequestParams() []CollectRequestParam4 {
	if c == nil {
		return nil
	}
	return c.CollectRequestParams
}

func (c *CollectorSplunkSplunk4) GetCollectRequestHeaders() []CollectorSplunkCollectRequestHeader4 {
	if c == nil {
		return nil
	}
	return c.CollectRequestHeaders
}

func (c *CollectorSplunkSplunk4) GetTimeout() *float64 {
	if c == nil {
		return nil
	}
	return c.Timeout
}

func (c *CollectorSplunkSplunk4) GetUseRoundRobinDNS() *bool {
	if c == nil {
		return nil
	}
	return c.UseRoundRobinDNS
}

func (c *CollectorSplunkSplunk4) GetDisableTimeFilter() *bool {
	if c == nil {
		return nil
	}
	return c.DisableTimeFilter
}

func (c *CollectorSplunkSplunk4) GetRejectUnauthorized() *bool {
	if c == nil {
		return nil
	}
	return c.RejectUnauthorized
}

func (c *CollectorSplunkSplunk4) GetHandleEscapedChars() *bool {
	if c == nil {
		return nil
	}
	return c.HandleEscapedChars
}

func (c *CollectorSplunkSplunk4) GetRetryRules() *CollectorSplunkRetryRules4 {
	if c == nil {
		return nil
	}
	return c.RetryRules
}

func (c *CollectorSplunkSplunk4) GetUsername() *string {
	if c == nil {
		return nil
	}
	return c.Username
}

func (c *CollectorSplunkSplunk4) GetPassword() *string {
	if c == nil {
		return nil
	}
	return c.Password
}

func (c *CollectorSplunkSplunk4) GetToken() *string {
	if c == nil {
		return nil
	}
	return c.Token
}

func (c *CollectorSplunkSplunk4) GetTokenSecret() *string {
	if c == nil {
		return nil
	}
	return c.TokenSecret
}

// CollectorSplunkAuthentication3 - Authentication method for Discover and Collect REST calls
type CollectorSplunkAuthentication3 string

const (
	// CollectorSplunkAuthentication3None None
	CollectorSplunkAuthentication3None CollectorSplunkAuthentication3 = "none"
	// CollectorSplunkAuthentication3Basic Basic
	CollectorSplunkAuthentication3Basic CollectorSplunkAuthentication3 = "basic"
	// CollectorSplunkAuthentication3BasicSecret Basic (credentials secret)
	CollectorSplunkAuthentication3BasicSecret CollectorSplunkAuthentication3 = "basicSecret"
	// CollectorSplunkAuthentication3Token Bearer Token
	CollectorSplunkAuthentication3Token CollectorSplunkAuthentication3 = "token"
	// CollectorSplunkAuthentication3TokenSecret Bearer Token (text secret)
	CollectorSplunkAuthentication3TokenSecret CollectorSplunkAuthentication3 = "tokenSecret"
)

func (e CollectorSplunkAuthentication3) ToPointer() *CollectorSplunkAuthentication3 {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CollectorSplunkAuthentication3) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "basic", "basicSecret", "token", "tokenSecret":
			return true
		}
	}
	return false
}

// CollectorSplunkType4 - Collector type: splunk
type CollectorSplunkType4 string

const (
	CollectorSplunkType4Splunk CollectorSplunkType4 = "splunk"
)

func (e CollectorSplunkType4) ToPointer() *CollectorSplunkType4 {
	return &e
}
func (e *CollectorSplunkType4) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "splunk":
		*e = CollectorSplunkType4(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CollectorSplunkType4: %v", v)
	}
}

type CollectRequestParam3 struct {
	Name string `json:"name"`
	// JavaScript expression to compute the parameter's value, normally enclosed in backticks (`${earliest}`). If a constant, use single quotes ('earliest'). Values without delimiters (earliest) are evaluated as strings.
	Value string `json:"value"`
}

func (c CollectRequestParam3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectRequestParam3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectRequestParam3) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CollectRequestParam3) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

type CollectorSplunkCollectRequestHeader3 struct {
	Name string `json:"name"`
	// JavaScript expression to compute the header's value, normally enclosed in backticks (`${earliest}`). If a constant, use single quotes ('earliest'). Values without delimiters (earliest) are evaluated as strings.
	Value string `json:"value"`
}

func (c CollectorSplunkCollectRequestHeader3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkCollectRequestHeader3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkCollectRequestHeader3) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CollectorSplunkCollectRequestHeader3) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

type CollectorSplunkRetryRules3 struct {
	// The algorithm to use when performing HTTP retries
	Type                *RetryTypeOptionsRetryRules `default:"backoff" json:"type"`
	Interval            any                         `json:"interval,omitempty"`
	Limit               any                         `json:"limit,omitempty"`
	Multiplier          any                         `json:"multiplier,omitempty"`
	Codes               any                         `json:"codes,omitempty"`
	EnableHeader        any                         `json:"enableHeader,omitempty"`
	RetryConnectTimeout any                         `json:"retryConnectTimeout,omitempty"`
	RetryConnectReset   any                         `json:"retryConnectReset,omitempty"`
}

func (c CollectorSplunkRetryRules3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkRetryRules3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkRetryRules3) GetType() *RetryTypeOptionsRetryRules {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CollectorSplunkRetryRules3) GetInterval() any {
	if c == nil {
		return nil
	}
	return c.Interval
}

func (c *CollectorSplunkRetryRules3) GetLimit() any {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *CollectorSplunkRetryRules3) GetMultiplier() any {
	if c == nil {
		return nil
	}
	return c.Multiplier
}

func (c *CollectorSplunkRetryRules3) GetCodes() any {
	if c == nil {
		return nil
	}
	return c.Codes
}

func (c *CollectorSplunkRetryRules3) GetEnableHeader() any {
	if c == nil {
		return nil
	}
	return c.EnableHeader
}

func (c *CollectorSplunkRetryRules3) GetRetryConnectTimeout() any {
	if c == nil {
		return nil
	}
	return c.RetryConnectTimeout
}

func (c *CollectorSplunkRetryRules3) GetRetryConnectReset() any {
	if c == nil {
		return nil
	}
	return c.RetryConnectReset
}

type CollectorSplunkSplunk3 struct {
	// Authentication method for Discover and Collect REST calls
	Authentication *CollectorSplunkAuthentication3 `default:"basic" json:"authentication"`
	// URL to use for login API call, this call is expected to be a POST.
	LoginURL *string `default:"https://localhost:9000/api/v1/auth/login" json:"loginUrl"`
	Username string  `json:"username"`
	Password string  `json:"password"`
	// Template for POST body to send with login request, ${username} and ${password} are used to specify location of these attributes in the message
	LoginBody *string `default:"{ \"username\": \"\\${username}\", \"password\": \"\\${password}\" }" json:"loginBody"`
	// Path to token attribute in login response body. Nested attributes are allowed.
	TokenRespAttribute *string `default:"token" json:"tokenRespAttribute"`
	// JavaScript expression to compute the Authorization header to pass in discover and collect calls. The value ${token} is used to reference the token obtained from login.
	AuthHeaderExpr *string `default:"Bearer \\${token}" json:"authHeaderExpr"`
	// Collector type: splunk
	Type CollectorSplunkType4 `json:"type"`
	// Search head base URL. Can be an expression. Default is https://localhost:8089.
	SearchHead *string `default:"https://localhost:8089" json:"searchHead"`
	// Examples: 'index=myAppLogs level=error channel=myApp' OR '| mstats avg(myStat) as myStat WHERE index=myStatsIndex.'
	Search string `json:"search"`
	// The earliest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-16m@m'
	Earliest *string `json:"earliest,omitempty"`
	// The latest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-1m@m'
	Latest *string `json:"latest,omitempty"`
	// REST API used to create a search
	Endpoint *string `default:"/services/search/v2/jobs/export" json:"endpoint"`
	// Format of the returned output
	OutputMode *OutputModeOptions `default:"json" json:"outputMode"`
	// Optional collect request parameters
	CollectRequestParams []CollectRequestParam3 `json:"collectRequestParams,omitempty"`
	// Optional collect request headers
	CollectRequestHeaders []CollectorSplunkCollectRequestHeader3 `json:"collectRequestHeaders,omitempty"`
	// HTTP request inactivity timeout. Use 0 for no timeout.
	Timeout *float64 `default:"0" json:"timeout"`
	// Use round-robin DNS lookup. Suitable when DNS server returns multiple addresses in sort order.
	UseRoundRobinDNS *bool `default:"false" json:"useRoundRobinDns"`
	// Disable collector event time filtering when a date range is specified
	DisableTimeFilter *bool `default:"true" json:"disableTimeFilter"`
	// Reject certificates that cannot be verified against a valid CA (such as self-signed certificates)
	RejectUnauthorized *bool `default:"false" json:"rejectUnauthorized"`
	// Escape characters (\") in search queries will be passed directly to Splunk
	HandleEscapedChars *bool                       `default:"false" json:"handleEscapedChars"`
	RetryRules         *CollectorSplunkRetryRules3 `json:"retryRules,omitempty"`
	// Select or create a stored secret that references your login credentials
	CredentialsSecret *string `json:"credentialsSecret,omitempty"`
	Token             *string `json:"token,omitempty"`
	// Select or create a stored secret that references your Bearer token
	TokenSecret *string `json:"tokenSecret,omitempty"`
}

func (c CollectorSplunkSplunk3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkSplunk3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"username", "password", "type", "search"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkSplunk3) GetAuthentication() *CollectorSplunkAuthentication3 {
	if c == nil {
		return nil
	}
	return c.Authentication
}

func (c *CollectorSplunkSplunk3) GetLoginURL() *string {
	if c == nil {
		return nil
	}
	return c.LoginURL
}

func (c *CollectorSplunkSplunk3) GetUsername() string {
	if c == nil {
		return ""
	}
	return c.Username
}

func (c *CollectorSplunkSplunk3) GetPassword() string {
	if c == nil {
		return ""
	}
	return c.Password
}

func (c *CollectorSplunkSplunk3) GetLoginBody() *string {
	if c == nil {
		return nil
	}
	return c.LoginBody
}

func (c *CollectorSplunkSplunk3) GetTokenRespAttribute() *string {
	if c == nil {
		return nil
	}
	return c.TokenRespAttribute
}

func (c *CollectorSplunkSplunk3) GetAuthHeaderExpr() *string {
	if c == nil {
		return nil
	}
	return c.AuthHeaderExpr
}

func (c *CollectorSplunkSplunk3) GetType() CollectorSplunkType4 {
	if c == nil {
		return CollectorSplunkType4("")
	}
	return c.Type
}

func (c *CollectorSplunkSplunk3) GetSearchHead() *string {
	if c == nil {
		return nil
	}
	return c.SearchHead
}

func (c *CollectorSplunkSplunk3) GetSearch() string {
	if c == nil {
		return ""
	}
	return c.Search
}

func (c *CollectorSplunkSplunk3) GetEarliest() *string {
	if c == nil {
		return nil
	}
	return c.Earliest
}

func (c *CollectorSplunkSplunk3) GetLatest() *string {
	if c == nil {
		return nil
	}
	return c.Latest
}

func (c *CollectorSplunkSplunk3) GetEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.Endpoint
}

func (c *CollectorSplunkSplunk3) GetOutputMode() *OutputModeOptions {
	if c == nil {
		return nil
	}
	return c.OutputMode
}

func (c *CollectorSplunkSplunk3) GetCollectRequestParams() []CollectRequestParam3 {
	if c == nil {
		return nil
	}
	return c.CollectRequestParams
}

func (c *CollectorSplunkSplunk3) GetCollectRequestHeaders() []CollectorSplunkCollectRequestHeader3 {
	if c == nil {
		return nil
	}
	return c.CollectRequestHeaders
}

func (c *CollectorSplunkSplunk3) GetTimeout() *float64 {
	if c == nil {
		return nil
	}
	return c.Timeout
}

func (c *CollectorSplunkSplunk3) GetUseRoundRobinDNS() *bool {
	if c == nil {
		return nil
	}
	return c.UseRoundRobinDNS
}

func (c *CollectorSplunkSplunk3) GetDisableTimeFilter() *bool {
	if c == nil {
		return nil
	}
	return c.DisableTimeFilter
}

func (c *CollectorSplunkSplunk3) GetRejectUnauthorized() *bool {
	if c == nil {
		return nil
	}
	return c.RejectUnauthorized
}

func (c *CollectorSplunkSplunk3) GetHandleEscapedChars() *bool {
	if c == nil {
		return nil
	}
	return c.HandleEscapedChars
}

func (c *CollectorSplunkSplunk3) GetRetryRules() *CollectorSplunkRetryRules3 {
	if c == nil {
		return nil
	}
	return c.RetryRules
}

func (c *CollectorSplunkSplunk3) GetCredentialsSecret() *string {
	if c == nil {
		return nil
	}
	return c.CredentialsSecret
}

func (c *CollectorSplunkSplunk3) GetToken() *string {
	if c == nil {
		return nil
	}
	return c.Token
}

func (c *CollectorSplunkSplunk3) GetTokenSecret() *string {
	if c == nil {
		return nil
	}
	return c.TokenSecret
}

// CollectorSplunkAuthentication2 - Authentication method for Discover and Collect REST calls
type CollectorSplunkAuthentication2 string

const (
	// CollectorSplunkAuthentication2None None
	CollectorSplunkAuthentication2None CollectorSplunkAuthentication2 = "none"
	// CollectorSplunkAuthentication2Basic Basic
	CollectorSplunkAuthentication2Basic CollectorSplunkAuthentication2 = "basic"
	// CollectorSplunkAuthentication2BasicSecret Basic (credentials secret)
	CollectorSplunkAuthentication2BasicSecret CollectorSplunkAuthentication2 = "basicSecret"
	// CollectorSplunkAuthentication2Token Bearer Token
	CollectorSplunkAuthentication2Token CollectorSplunkAuthentication2 = "token"
	// CollectorSplunkAuthentication2TokenSecret Bearer Token (text secret)
	CollectorSplunkAuthentication2TokenSecret CollectorSplunkAuthentication2 = "tokenSecret"
)

func (e CollectorSplunkAuthentication2) ToPointer() *CollectorSplunkAuthentication2 {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CollectorSplunkAuthentication2) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "basic", "basicSecret", "token", "tokenSecret":
			return true
		}
	}
	return false
}

// CollectorSplunkType3 - Collector type: splunk
type CollectorSplunkType3 string

const (
	CollectorSplunkType3Splunk CollectorSplunkType3 = "splunk"
)

func (e CollectorSplunkType3) ToPointer() *CollectorSplunkType3 {
	return &e
}
func (e *CollectorSplunkType3) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "splunk":
		*e = CollectorSplunkType3(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CollectorSplunkType3: %v", v)
	}
}

type CollectRequestParam2 struct {
	Name string `json:"name"`
	// JavaScript expression to compute the parameter's value, normally enclosed in backticks (`${earliest}`). If a constant, use single quotes ('earliest'). Values without delimiters (earliest) are evaluated as strings.
	Value string `json:"value"`
}

func (c CollectRequestParam2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectRequestParam2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectRequestParam2) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CollectRequestParam2) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

type CollectorSplunkCollectRequestHeader2 struct {
	Name string `json:"name"`
	// JavaScript expression to compute the header's value, normally enclosed in backticks (`${earliest}`). If a constant, use single quotes ('earliest'). Values without delimiters (earliest) are evaluated as strings.
	Value string `json:"value"`
}

func (c CollectorSplunkCollectRequestHeader2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkCollectRequestHeader2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkCollectRequestHeader2) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CollectorSplunkCollectRequestHeader2) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

type CollectorSplunkRetryRules2 struct {
	// The algorithm to use when performing HTTP retries
	Type                *RetryTypeOptionsRetryRules `default:"backoff" json:"type"`
	Interval            any                         `json:"interval,omitempty"`
	Limit               any                         `json:"limit,omitempty"`
	Multiplier          any                         `json:"multiplier,omitempty"`
	Codes               any                         `json:"codes,omitempty"`
	EnableHeader        any                         `json:"enableHeader,omitempty"`
	RetryConnectTimeout any                         `json:"retryConnectTimeout,omitempty"`
	RetryConnectReset   any                         `json:"retryConnectReset,omitempty"`
}

func (c CollectorSplunkRetryRules2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkRetryRules2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkRetryRules2) GetType() *RetryTypeOptionsRetryRules {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CollectorSplunkRetryRules2) GetInterval() any {
	if c == nil {
		return nil
	}
	return c.Interval
}

func (c *CollectorSplunkRetryRules2) GetLimit() any {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *CollectorSplunkRetryRules2) GetMultiplier() any {
	if c == nil {
		return nil
	}
	return c.Multiplier
}

func (c *CollectorSplunkRetryRules2) GetCodes() any {
	if c == nil {
		return nil
	}
	return c.Codes
}

func (c *CollectorSplunkRetryRules2) GetEnableHeader() any {
	if c == nil {
		return nil
	}
	return c.EnableHeader
}

func (c *CollectorSplunkRetryRules2) GetRetryConnectTimeout() any {
	if c == nil {
		return nil
	}
	return c.RetryConnectTimeout
}

func (c *CollectorSplunkRetryRules2) GetRetryConnectReset() any {
	if c == nil {
		return nil
	}
	return c.RetryConnectReset
}

type CollectorSplunkSplunk2 struct {
	// Authentication method for Discover and Collect REST calls
	Authentication *CollectorSplunkAuthentication2 `default:"basic" json:"authentication"`
	// Select or create a stored secret that references your Bearer token
	TokenSecret string `json:"tokenSecret"`
	// Collector type: splunk
	Type CollectorSplunkType3 `json:"type"`
	// Search head base URL. Can be an expression. Default is https://localhost:8089.
	SearchHead *string `default:"https://localhost:8089" json:"searchHead"`
	// Examples: 'index=myAppLogs level=error channel=myApp' OR '| mstats avg(myStat) as myStat WHERE index=myStatsIndex.'
	Search string `json:"search"`
	// The earliest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-16m@m'
	Earliest *string `json:"earliest,omitempty"`
	// The latest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-1m@m'
	Latest *string `json:"latest,omitempty"`
	// REST API used to create a search
	Endpoint *string `default:"/services/search/v2/jobs/export" json:"endpoint"`
	// Format of the returned output
	OutputMode *OutputModeOptions `default:"json" json:"outputMode"`
	// Optional collect request parameters
	CollectRequestParams []CollectRequestParam2 `json:"collectRequestParams,omitempty"`
	// Optional collect request headers
	CollectRequestHeaders []CollectorSplunkCollectRequestHeader2 `json:"collectRequestHeaders,omitempty"`
	// HTTP request inactivity timeout. Use 0 for no timeout.
	Timeout *float64 `default:"0" json:"timeout"`
	// Use round-robin DNS lookup. Suitable when DNS server returns multiple addresses in sort order.
	UseRoundRobinDNS *bool `default:"false" json:"useRoundRobinDns"`
	// Disable collector event time filtering when a date range is specified
	DisableTimeFilter *bool `default:"true" json:"disableTimeFilter"`
	// Reject certificates that cannot be verified against a valid CA (such as self-signed certificates)
	RejectUnauthorized *bool `default:"false" json:"rejectUnauthorized"`
	// Escape characters (\") in search queries will be passed directly to Splunk
	HandleEscapedChars *bool                       `default:"false" json:"handleEscapedChars"`
	RetryRules         *CollectorSplunkRetryRules2 `json:"retryRules,omitempty"`
	Username           *string                     `json:"username,omitempty"`
	Password           *string                     `json:"password,omitempty"`
	// Select or create a stored secret that references your login credentials
	CredentialsSecret *string `json:"credentialsSecret,omitempty"`
	Token             *string `json:"token,omitempty"`
	// URL to use for login API call, this call is expected to be a POST.
	LoginURL *string `default:"https://localhost:9000/api/v1/auth/login" json:"loginUrl"`
	// Template for POST body to send with login request, ${username} and ${password} are used to specify location of these attributes in the message
	LoginBody *string `default:"{ \"username\": \"\\${username}\", \"password\": \"\\${password}\" }" json:"loginBody"`
	// Path to token attribute in login response body. Nested attributes are allowed.
	TokenRespAttribute *string `default:"token" json:"tokenRespAttribute"`
	// JavaScript expression to compute the Authorization header to pass in discover and collect calls. The value ${token} is used to reference the token obtained from login.
	AuthHeaderExpr *string `default:"Bearer \\${token}" json:"authHeaderExpr"`
}

func (c CollectorSplunkSplunk2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkSplunk2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"tokenSecret", "type", "search"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkSplunk2) GetAuthentication() *CollectorSplunkAuthentication2 {
	if c == nil {
		return nil
	}
	return c.Authentication
}

func (c *CollectorSplunkSplunk2) GetTokenSecret() string {
	if c == nil {
		return ""
	}
	return c.TokenSecret
}

func (c *CollectorSplunkSplunk2) GetType() CollectorSplunkType3 {
	if c == nil {
		return CollectorSplunkType3("")
	}
	return c.Type
}

func (c *CollectorSplunkSplunk2) GetSearchHead() *string {
	if c == nil {
		return nil
	}
	return c.SearchHead
}

func (c *CollectorSplunkSplunk2) GetSearch() string {
	if c == nil {
		return ""
	}
	return c.Search
}

func (c *CollectorSplunkSplunk2) GetEarliest() *string {
	if c == nil {
		return nil
	}
	return c.Earliest
}

func (c *CollectorSplunkSplunk2) GetLatest() *string {
	if c == nil {
		return nil
	}
	return c.Latest
}

func (c *CollectorSplunkSplunk2) GetEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.Endpoint
}

func (c *CollectorSplunkSplunk2) GetOutputMode() *OutputModeOptions {
	if c == nil {
		return nil
	}
	return c.OutputMode
}

func (c *CollectorSplunkSplunk2) GetCollectRequestParams() []CollectRequestParam2 {
	if c == nil {
		return nil
	}
	return c.CollectRequestParams
}

func (c *CollectorSplunkSplunk2) GetCollectRequestHeaders() []CollectorSplunkCollectRequestHeader2 {
	if c == nil {
		return nil
	}
	return c.CollectRequestHeaders
}

func (c *CollectorSplunkSplunk2) GetTimeout() *float64 {
	if c == nil {
		return nil
	}
	return c.Timeout
}

func (c *CollectorSplunkSplunk2) GetUseRoundRobinDNS() *bool {
	if c == nil {
		return nil
	}
	return c.UseRoundRobinDNS
}

func (c *CollectorSplunkSplunk2) GetDisableTimeFilter() *bool {
	if c == nil {
		return nil
	}
	return c.DisableTimeFilter
}

func (c *CollectorSplunkSplunk2) GetRejectUnauthorized() *bool {
	if c == nil {
		return nil
	}
	return c.RejectUnauthorized
}

func (c *CollectorSplunkSplunk2) GetHandleEscapedChars() *bool {
	if c == nil {
		return nil
	}
	return c.HandleEscapedChars
}

func (c *CollectorSplunkSplunk2) GetRetryRules() *CollectorSplunkRetryRules2 {
	if c == nil {
		return nil
	}
	return c.RetryRules
}

func (c *CollectorSplunkSplunk2) GetUsername() *string {
	if c == nil {
		return nil
	}
	return c.Username
}

func (c *CollectorSplunkSplunk2) GetPassword() *string {
	if c == nil {
		return nil
	}
	return c.Password
}

func (c *CollectorSplunkSplunk2) GetCredentialsSecret() *string {
	if c == nil {
		return nil
	}
	return c.CredentialsSecret
}

func (c *CollectorSplunkSplunk2) GetToken() *string {
	if c == nil {
		return nil
	}
	return c.Token
}

func (c *CollectorSplunkSplunk2) GetLoginURL() *string {
	if c == nil {
		return nil
	}
	return c.LoginURL
}

func (c *CollectorSplunkSplunk2) GetLoginBody() *string {
	if c == nil {
		return nil
	}
	return c.LoginBody
}

func (c *CollectorSplunkSplunk2) GetTokenRespAttribute() *string {
	if c == nil {
		return nil
	}
	return c.TokenRespAttribute
}

func (c *CollectorSplunkSplunk2) GetAuthHeaderExpr() *string {
	if c == nil {
		return nil
	}
	return c.AuthHeaderExpr
}

// CollectorSplunkAuthentication1 - Authentication method for Discover and Collect REST calls
type CollectorSplunkAuthentication1 string

const (
	// CollectorSplunkAuthentication1None None
	CollectorSplunkAuthentication1None CollectorSplunkAuthentication1 = "none"
	// CollectorSplunkAuthentication1Basic Basic
	CollectorSplunkAuthentication1Basic CollectorSplunkAuthentication1 = "basic"
	// CollectorSplunkAuthentication1BasicSecret Basic (credentials secret)
	CollectorSplunkAuthentication1BasicSecret CollectorSplunkAuthentication1 = "basicSecret"
	// CollectorSplunkAuthentication1Token Bearer Token
	CollectorSplunkAuthentication1Token CollectorSplunkAuthentication1 = "token"
	// CollectorSplunkAuthentication1TokenSecret Bearer Token (text secret)
	CollectorSplunkAuthentication1TokenSecret CollectorSplunkAuthentication1 = "tokenSecret"
)

func (e CollectorSplunkAuthentication1) ToPointer() *CollectorSplunkAuthentication1 {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CollectorSplunkAuthentication1) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "basic", "basicSecret", "token", "tokenSecret":
			return true
		}
	}
	return false
}

// CollectorSplunkType2 - Collector type: splunk
type CollectorSplunkType2 string

const (
	CollectorSplunkType2Splunk CollectorSplunkType2 = "splunk"
)

func (e CollectorSplunkType2) ToPointer() *CollectorSplunkType2 {
	return &e
}
func (e *CollectorSplunkType2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "splunk":
		*e = CollectorSplunkType2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CollectorSplunkType2: %v", v)
	}
}

type CollectRequestParam1 struct {
	Name string `json:"name"`
	// JavaScript expression to compute the parameter's value, normally enclosed in backticks (`${earliest}`). If a constant, use single quotes ('earliest'). Values without delimiters (earliest) are evaluated as strings.
	Value string `json:"value"`
}

func (c CollectRequestParam1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectRequestParam1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectRequestParam1) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CollectRequestParam1) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

type CollectorSplunkCollectRequestHeader1 struct {
	Name string `json:"name"`
	// JavaScript expression to compute the header's value, normally enclosed in backticks (`${earliest}`). If a constant, use single quotes ('earliest'). Values without delimiters (earliest) are evaluated as strings.
	Value string `json:"value"`
}

func (c CollectorSplunkCollectRequestHeader1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkCollectRequestHeader1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkCollectRequestHeader1) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CollectorSplunkCollectRequestHeader1) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

type CollectorSplunkRetryRules1 struct {
	// The algorithm to use when performing HTTP retries
	Type                *RetryTypeOptionsRetryRules `default:"backoff" json:"type"`
	Interval            any                         `json:"interval,omitempty"`
	Limit               any                         `json:"limit,omitempty"`
	Multiplier          any                         `json:"multiplier,omitempty"`
	Codes               any                         `json:"codes,omitempty"`
	EnableHeader        any                         `json:"enableHeader,omitempty"`
	RetryConnectTimeout any                         `json:"retryConnectTimeout,omitempty"`
	RetryConnectReset   any                         `json:"retryConnectReset,omitempty"`
}

func (c CollectorSplunkRetryRules1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkRetryRules1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkRetryRules1) GetType() *RetryTypeOptionsRetryRules {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CollectorSplunkRetryRules1) GetInterval() any {
	if c == nil {
		return nil
	}
	return c.Interval
}

func (c *CollectorSplunkRetryRules1) GetLimit() any {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *CollectorSplunkRetryRules1) GetMultiplier() any {
	if c == nil {
		return nil
	}
	return c.Multiplier
}

func (c *CollectorSplunkRetryRules1) GetCodes() any {
	if c == nil {
		return nil
	}
	return c.Codes
}

func (c *CollectorSplunkRetryRules1) GetEnableHeader() any {
	if c == nil {
		return nil
	}
	return c.EnableHeader
}

func (c *CollectorSplunkRetryRules1) GetRetryConnectTimeout() any {
	if c == nil {
		return nil
	}
	return c.RetryConnectTimeout
}

func (c *CollectorSplunkRetryRules1) GetRetryConnectReset() any {
	if c == nil {
		return nil
	}
	return c.RetryConnectReset
}

type CollectorSplunkSplunk1 struct {
	// Authentication method for Discover and Collect REST calls
	Authentication *CollectorSplunkAuthentication1 `default:"basic" json:"authentication"`
	Token          string                          `json:"token"`
	// Collector type: splunk
	Type CollectorSplunkType2 `json:"type"`
	// Search head base URL. Can be an expression. Default is https://localhost:8089.
	SearchHead *string `default:"https://localhost:8089" json:"searchHead"`
	// Examples: 'index=myAppLogs level=error channel=myApp' OR '| mstats avg(myStat) as myStat WHERE index=myStatsIndex.'
	Search string `json:"search"`
	// The earliest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-16m@m'
	Earliest *string `json:"earliest,omitempty"`
	// The latest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-1m@m'
	Latest *string `json:"latest,omitempty"`
	// REST API used to create a search
	Endpoint *string `default:"/services/search/v2/jobs/export" json:"endpoint"`
	// Format of the returned output
	OutputMode *OutputModeOptions `default:"json" json:"outputMode"`
	// Optional collect request parameters
	CollectRequestParams []CollectRequestParam1 `json:"collectRequestParams,omitempty"`
	// Optional collect request headers
	CollectRequestHeaders []CollectorSplunkCollectRequestHeader1 `json:"collectRequestHeaders,omitempty"`
	// HTTP request inactivity timeout. Use 0 for no timeout.
	Timeout *float64 `default:"0" json:"timeout"`
	// Use round-robin DNS lookup. Suitable when DNS server returns multiple addresses in sort order.
	UseRoundRobinDNS *bool `default:"false" json:"useRoundRobinDns"`
	// Disable collector event time filtering when a date range is specified
	DisableTimeFilter *bool `default:"true" json:"disableTimeFilter"`
	// Reject certificates that cannot be verified against a valid CA (such as self-signed certificates)
	RejectUnauthorized *bool `default:"false" json:"rejectUnauthorized"`
	// Escape characters (\") in search queries will be passed directly to Splunk
	HandleEscapedChars *bool                       `default:"false" json:"handleEscapedChars"`
	RetryRules         *CollectorSplunkRetryRules1 `json:"retryRules,omitempty"`
	Username           *string                     `json:"username,omitempty"`
	Password           *string                     `json:"password,omitempty"`
	// Select or create a stored secret that references your login credentials
	CredentialsSecret *string `json:"credentialsSecret,omitempty"`
	// Select or create a stored secret that references your Bearer token
	TokenSecret *string `json:"tokenSecret,omitempty"`
	// URL to use for login API call, this call is expected to be a POST.
	LoginURL *string `default:"https://localhost:9000/api/v1/auth/login" json:"loginUrl"`
	// Template for POST body to send with login request, ${username} and ${password} are used to specify location of these attributes in the message
	LoginBody *string `default:"{ \"username\": \"\\${username}\", \"password\": \"\\${password}\" }" json:"loginBody"`
	// Path to token attribute in login response body. Nested attributes are allowed.
	TokenRespAttribute *string `default:"token" json:"tokenRespAttribute"`
	// JavaScript expression to compute the Authorization header to pass in discover and collect calls. The value ${token} is used to reference the token obtained from login.
	AuthHeaderExpr *string `default:"Bearer \\${token}" json:"authHeaderExpr"`
}

func (c CollectorSplunkSplunk1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkSplunk1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"token", "type", "search"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkSplunk1) GetAuthentication() *CollectorSplunkAuthentication1 {
	if c == nil {
		return nil
	}
	return c.Authentication
}

func (c *CollectorSplunkSplunk1) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *CollectorSplunkSplunk1) GetType() CollectorSplunkType2 {
	if c == nil {
		return CollectorSplunkType2("")
	}
	return c.Type
}

func (c *CollectorSplunkSplunk1) GetSearchHead() *string {
	if c == nil {
		return nil
	}
	return c.SearchHead
}

func (c *CollectorSplunkSplunk1) GetSearch() string {
	if c == nil {
		return ""
	}
	return c.Search
}

func (c *CollectorSplunkSplunk1) GetEarliest() *string {
	if c == nil {
		return nil
	}
	return c.Earliest
}

func (c *CollectorSplunkSplunk1) GetLatest() *string {
	if c == nil {
		return nil
	}
	return c.Latest
}

func (c *CollectorSplunkSplunk1) GetEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.Endpoint
}

func (c *CollectorSplunkSplunk1) GetOutputMode() *OutputModeOptions {
	if c == nil {
		return nil
	}
	return c.OutputMode
}

func (c *CollectorSplunkSplunk1) GetCollectRequestParams() []CollectRequestParam1 {
	if c == nil {
		return nil
	}
	return c.CollectRequestParams
}

func (c *CollectorSplunkSplunk1) GetCollectRequestHeaders() []CollectorSplunkCollectRequestHeader1 {
	if c == nil {
		return nil
	}
	return c.CollectRequestHeaders
}

func (c *CollectorSplunkSplunk1) GetTimeout() *float64 {
	if c == nil {
		return nil
	}
	return c.Timeout
}

func (c *CollectorSplunkSplunk1) GetUseRoundRobinDNS() *bool {
	if c == nil {
		return nil
	}
	return c.UseRoundRobinDNS
}

func (c *CollectorSplunkSplunk1) GetDisableTimeFilter() *bool {
	if c == nil {
		return nil
	}
	return c.DisableTimeFilter
}

func (c *CollectorSplunkSplunk1) GetRejectUnauthorized() *bool {
	if c == nil {
		return nil
	}
	return c.RejectUnauthorized
}

func (c *CollectorSplunkSplunk1) GetHandleEscapedChars() *bool {
	if c == nil {
		return nil
	}
	return c.HandleEscapedChars
}

func (c *CollectorSplunkSplunk1) GetRetryRules() *CollectorSplunkRetryRules1 {
	if c == nil {
		return nil
	}
	return c.RetryRules
}

func (c *CollectorSplunkSplunk1) GetUsername() *string {
	if c == nil {
		return nil
	}
	return c.Username
}

func (c *CollectorSplunkSplunk1) GetPassword() *string {
	if c == nil {
		return nil
	}
	return c.Password
}

func (c *CollectorSplunkSplunk1) GetCredentialsSecret() *string {
	if c == nil {
		return nil
	}
	return c.CredentialsSecret
}

func (c *CollectorSplunkSplunk1) GetTokenSecret() *string {
	if c == nil {
		return nil
	}
	return c.TokenSecret
}

func (c *CollectorSplunkSplunk1) GetLoginURL() *string {
	if c == nil {
		return nil
	}
	return c.LoginURL
}

func (c *CollectorSplunkSplunk1) GetLoginBody() *string {
	if c == nil {
		return nil
	}
	return c.LoginBody
}

func (c *CollectorSplunkSplunk1) GetTokenRespAttribute() *string {
	if c == nil {
		return nil
	}
	return c.TokenRespAttribute
}

func (c *CollectorSplunkSplunk1) GetAuthHeaderExpr() *string {
	if c == nil {
		return nil
	}
	return c.AuthHeaderExpr
}

type CollectorSplunkCollectorHealthCheckPart2Type struct {
	// Authentication method for Discover and Collect REST calls
	Authentication *AuthenticationSplunk `default:"basic" json:"authentication"`
	// Select or create a stored secret that references your login credentials
	CredentialsSecret string `json:"credentialsSecret"`
	// Collector type: splunk
	Type CollectorSplunkType1 `json:"type"`
	// Search head base URL. Can be an expression. Default is https://localhost:8089.
	SearchHead *string `default:"https://localhost:8089" json:"searchHead"`
	// Examples: 'index=myAppLogs level=error channel=myApp' OR '| mstats avg(myStat) as myStat WHERE index=myStatsIndex.'
	Search string `json:"search"`
	// The earliest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-16m@m'
	Earliest *string `json:"earliest,omitempty"`
	// The latest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-1m@m'
	Latest *string `json:"latest,omitempty"`
	// REST API used to create a search
	Endpoint *string `default:"/services/search/v2/jobs/export" json:"endpoint"`
	// Format of the returned output
	OutputMode *OutputModeOptions `default:"json" json:"outputMode"`
	// Optional collect request parameters
	CollectRequestParams []CollectRequestParamSplunk `json:"collectRequestParams,omitempty"`
	// Optional collect request headers
	CollectRequestHeaders []CollectRequestHeaderSplunk `json:"collectRequestHeaders,omitempty"`
	// HTTP request inactivity timeout. Use 0 for no timeout.
	Timeout *float64 `default:"0" json:"timeout"`
	// Use round-robin DNS lookup. Suitable when DNS server returns multiple addresses in sort order.
	UseRoundRobinDNS *bool `default:"false" json:"useRoundRobinDns"`
	// Disable collector event time filtering when a date range is specified
	DisableTimeFilter *bool `default:"true" json:"disableTimeFilter"`
	// Reject certificates that cannot be verified against a valid CA (such as self-signed certificates)
	RejectUnauthorized *bool `default:"false" json:"rejectUnauthorized"`
	// Escape characters (\") in search queries will be passed directly to Splunk
	HandleEscapedChars *bool             `default:"false" json:"handleEscapedChars"`
	RetryRules         *RetryRulesSplunk `json:"retryRules,omitempty"`
	Username           *string           `json:"username,omitempty"`
	Password           *string           `json:"password,omitempty"`
	Token              *string           `json:"token,omitempty"`
	// Select or create a stored secret that references your Bearer token
	TokenSecret *string `json:"tokenSecret,omitempty"`
	// URL to use for login API call, this call is expected to be a POST.
	LoginURL *string `default:"https://localhost:9000/api/v1/auth/login" json:"loginUrl"`
	// Template for POST body to send with login request, ${username} and ${password} are used to specify location of these attributes in the message
	LoginBody *string `default:"{ \"username\": \"\\${username}\", \"password\": \"\\${password}\" }" json:"loginBody"`
	// Path to token attribute in login response body. Nested attributes are allowed.
	TokenRespAttribute *string `default:"token" json:"tokenRespAttribute"`
	// JavaScript expression to compute the Authorization header to pass in discover and collect calls. The value ${token} is used to reference the token obtained from login.
	AuthHeaderExpr *string `default:"Bearer \\${token}" json:"authHeaderExpr"`
}

func (c CollectorSplunkCollectorHealthCheckPart2Type) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"credentialsSecret", "type", "search"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetAuthentication() *AuthenticationSplunk {
	if c == nil {
		return nil
	}
	return c.Authentication
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetCredentialsSecret() string {
	if c == nil {
		return ""
	}
	return c.CredentialsSecret
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetType() CollectorSplunkType1 {
	if c == nil {
		return CollectorSplunkType1("")
	}
	return c.Type
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetSearchHead() *string {
	if c == nil {
		return nil
	}
	return c.SearchHead
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetSearch() string {
	if c == nil {
		return ""
	}
	return c.Search
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetEarliest() *string {
	if c == nil {
		return nil
	}
	return c.Earliest
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetLatest() *string {
	if c == nil {
		return nil
	}
	return c.Latest
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.Endpoint
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetOutputMode() *OutputModeOptions {
	if c == nil {
		return nil
	}
	return c.OutputMode
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetCollectRequestParams() []CollectRequestParamSplunk {
	if c == nil {
		return nil
	}
	return c.CollectRequestParams
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetCollectRequestHeaders() []CollectRequestHeaderSplunk {
	if c == nil {
		return nil
	}
	return c.CollectRequestHeaders
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetTimeout() *float64 {
	if c == nil {
		return nil
	}
	return c.Timeout
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetUseRoundRobinDNS() *bool {
	if c == nil {
		return nil
	}
	return c.UseRoundRobinDNS
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetDisableTimeFilter() *bool {
	if c == nil {
		return nil
	}
	return c.DisableTimeFilter
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetRejectUnauthorized() *bool {
	if c == nil {
		return nil
	}
	return c.RejectUnauthorized
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetHandleEscapedChars() *bool {
	if c == nil {
		return nil
	}
	return c.HandleEscapedChars
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetRetryRules() *RetryRulesSplunk {
	if c == nil {
		return nil
	}
	return c.RetryRules
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetUsername() *string {
	if c == nil {
		return nil
	}
	return c.Username
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetPassword() *string {
	if c == nil {
		return nil
	}
	return c.Password
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetToken() *string {
	if c == nil {
		return nil
	}
	return c.Token
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetTokenSecret() *string {
	if c == nil {
		return nil
	}
	return c.TokenSecret
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetLoginURL() *string {
	if c == nil {
		return nil
	}
	return c.LoginURL
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetLoginBody() *string {
	if c == nil {
		return nil
	}
	return c.LoginBody
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetTokenRespAttribute() *string {
	if c == nil {
		return nil
	}
	return c.TokenRespAttribute
}

func (c *CollectorSplunkCollectorHealthCheckPart2Type) GetAuthHeaderExpr() *string {
	if c == nil {
		return nil
	}
	return c.AuthHeaderExpr
}

type CollectorSplunkCollectorHealthCheckPart1Type struct {
	// Authentication method for Discover and Collect REST calls
	Authentication *AuthenticationSplunk `default:"basic" json:"authentication"`
	Username       string                `json:"username"`
	Password       string                `json:"password"`
	// Collector type: splunk
	Type CollectorSplunkType1 `json:"type"`
	// Search head base URL. Can be an expression. Default is https://localhost:8089.
	SearchHead *string `default:"https://localhost:8089" json:"searchHead"`
	// Examples: 'index=myAppLogs level=error channel=myApp' OR '| mstats avg(myStat) as myStat WHERE index=myStatsIndex.'
	Search string `json:"search"`
	// The earliest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-16m@m'
	Earliest *string `json:"earliest,omitempty"`
	// The latest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-1m@m'
	Latest *string `json:"latest,omitempty"`
	// REST API used to create a search
	Endpoint *string `default:"/services/search/v2/jobs/export" json:"endpoint"`
	// Format of the returned output
	OutputMode *OutputModeOptions `default:"json" json:"outputMode"`
	// Optional collect request parameters
	CollectRequestParams []CollectRequestParamSplunk `json:"collectRequestParams,omitempty"`
	// Optional collect request headers
	CollectRequestHeaders []CollectRequestHeaderSplunk `json:"collectRequestHeaders,omitempty"`
	// HTTP request inactivity timeout. Use 0 for no timeout.
	Timeout *float64 `default:"0" json:"timeout"`
	// Use round-robin DNS lookup. Suitable when DNS server returns multiple addresses in sort order.
	UseRoundRobinDNS *bool `default:"false" json:"useRoundRobinDns"`
	// Disable collector event time filtering when a date range is specified
	DisableTimeFilter *bool `default:"true" json:"disableTimeFilter"`
	// Reject certificates that cannot be verified against a valid CA (such as self-signed certificates)
	RejectUnauthorized *bool `default:"false" json:"rejectUnauthorized"`
	// Escape characters (\") in search queries will be passed directly to Splunk
	HandleEscapedChars *bool             `default:"false" json:"handleEscapedChars"`
	RetryRules         *RetryRulesSplunk `json:"retryRules,omitempty"`
	// Select or create a stored secret that references your login credentials
	CredentialsSecret *string `json:"credentialsSecret,omitempty"`
	Token             *string `json:"token,omitempty"`
	// Select or create a stored secret that references your Bearer token
	TokenSecret *string `json:"tokenSecret,omitempty"`
	// URL to use for login API call, this call is expected to be a POST.
	LoginURL *string `default:"https://localhost:9000/api/v1/auth/login" json:"loginUrl"`
	// Template for POST body to send with login request, ${username} and ${password} are used to specify location of these attributes in the message
	LoginBody *string `default:"{ \"username\": \"\\${username}\", \"password\": \"\\${password}\" }" json:"loginBody"`
	// Path to token attribute in login response body. Nested attributes are allowed.
	TokenRespAttribute *string `default:"token" json:"tokenRespAttribute"`
	// JavaScript expression to compute the Authorization header to pass in discover and collect calls. The value ${token} is used to reference the token obtained from login.
	AuthHeaderExpr *string `default:"Bearer \\${token}" json:"authHeaderExpr"`
}

func (c CollectorSplunkCollectorHealthCheckPart1Type) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"username", "password", "type", "search"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetAuthentication() *AuthenticationSplunk {
	if c == nil {
		return nil
	}
	return c.Authentication
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetUsername() string {
	if c == nil {
		return ""
	}
	return c.Username
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetPassword() string {
	if c == nil {
		return ""
	}
	return c.Password
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetType() CollectorSplunkType1 {
	if c == nil {
		return CollectorSplunkType1("")
	}
	return c.Type
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetSearchHead() *string {
	if c == nil {
		return nil
	}
	return c.SearchHead
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetSearch() string {
	if c == nil {
		return ""
	}
	return c.Search
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetEarliest() *string {
	if c == nil {
		return nil
	}
	return c.Earliest
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetLatest() *string {
	if c == nil {
		return nil
	}
	return c.Latest
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.Endpoint
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetOutputMode() *OutputModeOptions {
	if c == nil {
		return nil
	}
	return c.OutputMode
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetCollectRequestParams() []CollectRequestParamSplunk {
	if c == nil {
		return nil
	}
	return c.CollectRequestParams
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetCollectRequestHeaders() []CollectRequestHeaderSplunk {
	if c == nil {
		return nil
	}
	return c.CollectRequestHeaders
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetTimeout() *float64 {
	if c == nil {
		return nil
	}
	return c.Timeout
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetUseRoundRobinDNS() *bool {
	if c == nil {
		return nil
	}
	return c.UseRoundRobinDNS
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetDisableTimeFilter() *bool {
	if c == nil {
		return nil
	}
	return c.DisableTimeFilter
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetRejectUnauthorized() *bool {
	if c == nil {
		return nil
	}
	return c.RejectUnauthorized
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetHandleEscapedChars() *bool {
	if c == nil {
		return nil
	}
	return c.HandleEscapedChars
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetRetryRules() *RetryRulesSplunk {
	if c == nil {
		return nil
	}
	return c.RetryRules
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetCredentialsSecret() *string {
	if c == nil {
		return nil
	}
	return c.CredentialsSecret
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetToken() *string {
	if c == nil {
		return nil
	}
	return c.Token
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetTokenSecret() *string {
	if c == nil {
		return nil
	}
	return c.TokenSecret
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetLoginURL() *string {
	if c == nil {
		return nil
	}
	return c.LoginURL
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetLoginBody() *string {
	if c == nil {
		return nil
	}
	return c.LoginBody
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetTokenRespAttribute() *string {
	if c == nil {
		return nil
	}
	return c.TokenRespAttribute
}

func (c *CollectorSplunkCollectorHealthCheckPart1Type) GetAuthHeaderExpr() *string {
	if c == nil {
		return nil
	}
	return c.AuthHeaderExpr
}

// AuthenticationSplunk - Authentication method for Discover and Collect REST calls
type AuthenticationSplunk string

const (
	// AuthenticationSplunkNone None
	AuthenticationSplunkNone AuthenticationSplunk = "none"
	// AuthenticationSplunkBasic Basic
	AuthenticationSplunkBasic AuthenticationSplunk = "basic"
	// AuthenticationSplunkBasicSecret Basic (credentials secret)
	AuthenticationSplunkBasicSecret AuthenticationSplunk = "basicSecret"
	// AuthenticationSplunkToken Bearer Token
	AuthenticationSplunkToken AuthenticationSplunk = "token"
	// AuthenticationSplunkTokenSecret Bearer Token (text secret)
	AuthenticationSplunkTokenSecret AuthenticationSplunk = "tokenSecret"
)

func (e AuthenticationSplunk) ToPointer() *AuthenticationSplunk {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AuthenticationSplunk) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "basic", "basicSecret", "token", "tokenSecret":
			return true
		}
	}
	return false
}

// CollectorSplunkType1 - Collector type: splunk
type CollectorSplunkType1 string

const (
	CollectorSplunkType1Splunk CollectorSplunkType1 = "splunk"
)

func (e CollectorSplunkType1) ToPointer() *CollectorSplunkType1 {
	return &e
}
func (e *CollectorSplunkType1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "splunk":
		*e = CollectorSplunkType1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CollectorSplunkType1: %v", v)
	}
}

type CollectRequestParamSplunk struct {
	Name string `json:"name"`
	// JavaScript expression to compute the parameter's value, normally enclosed in backticks (`${earliest}`). If a constant, use single quotes ('earliest'). Values without delimiters (earliest) are evaluated as strings.
	Value string `json:"value"`
}

func (c CollectRequestParamSplunk) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectRequestParamSplunk) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectRequestParamSplunk) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CollectRequestParamSplunk) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

type CollectRequestHeaderSplunk struct {
	Name string `json:"name"`
	// JavaScript expression to compute the header's value, normally enclosed in backticks (`${earliest}`). If a constant, use single quotes ('earliest'). Values without delimiters (earliest) are evaluated as strings.
	Value string `json:"value"`
}

func (c CollectRequestHeaderSplunk) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectRequestHeaderSplunk) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectRequestHeaderSplunk) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CollectRequestHeaderSplunk) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

type RetryRulesSplunk struct {
	// The algorithm to use when performing HTTP retries
	Type                *RetryTypeOptionsRetryRules `default:"backoff" json:"type"`
	Interval            any                         `json:"interval,omitempty"`
	Limit               any                         `json:"limit,omitempty"`
	Multiplier          any                         `json:"multiplier,omitempty"`
	Codes               any                         `json:"codes,omitempty"`
	EnableHeader        any                         `json:"enableHeader,omitempty"`
	RetryConnectTimeout any                         `json:"retryConnectTimeout,omitempty"`
	RetryConnectReset   any                         `json:"retryConnectReset,omitempty"`
}

func (r RetryRulesSplunk) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RetryRulesSplunk) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RetryRulesSplunk) GetType() *RetryTypeOptionsRetryRules {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *RetryRulesSplunk) GetInterval() any {
	if r == nil {
		return nil
	}
	return r.Interval
}

func (r *RetryRulesSplunk) GetLimit() any {
	if r == nil {
		return nil
	}
	return r.Limit
}

func (r *RetryRulesSplunk) GetMultiplier() any {
	if r == nil {
		return nil
	}
	return r.Multiplier
}

func (r *RetryRulesSplunk) GetCodes() any {
	if r == nil {
		return nil
	}
	return r.Codes
}

func (r *RetryRulesSplunk) GetEnableHeader() any {
	if r == nil {
		return nil
	}
	return r.EnableHeader
}

func (r *RetryRulesSplunk) GetRetryConnectTimeout() any {
	if r == nil {
		return nil
	}
	return r.RetryConnectTimeout
}

func (r *RetryRulesSplunk) GetRetryConnectReset() any {
	if r == nil {
		return nil
	}
	return r.RetryConnectReset
}

type CollectorSplunkCollectorHealthCheckPart0Type struct {
	// Authentication method for Discover and Collect REST calls
	Authentication *AuthenticationSplunk `default:"basic" json:"authentication"`
	// Collector type: splunk
	Type CollectorSplunkType1 `json:"type"`
	// Search head base URL. Can be an expression. Default is https://localhost:8089.
	SearchHead *string `default:"https://localhost:8089" json:"searchHead"`
	// Examples: 'index=myAppLogs level=error channel=myApp' OR '| mstats avg(myStat) as myStat WHERE index=myStatsIndex.'
	Search string `json:"search"`
	// The earliest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-16m@m'
	Earliest *string `json:"earliest,omitempty"`
	// The latest time boundary for the search. Can be an exact or relative time. Examples: '2022-01-14T12:00:00Z' or '-1m@m'
	Latest *string `json:"latest,omitempty"`
	// REST API used to create a search
	Endpoint *string `default:"/services/search/v2/jobs/export" json:"endpoint"`
	// Format of the returned output
	OutputMode *OutputModeOptions `default:"json" json:"outputMode"`
	// Optional collect request parameters
	CollectRequestParams []CollectRequestParamSplunk `json:"collectRequestParams,omitempty"`
	// Optional collect request headers
	CollectRequestHeaders []CollectRequestHeaderSplunk `json:"collectRequestHeaders,omitempty"`
	// HTTP request inactivity timeout. Use 0 for no timeout.
	Timeout *float64 `default:"0" json:"timeout"`
	// Use round-robin DNS lookup. Suitable when DNS server returns multiple addresses in sort order.
	UseRoundRobinDNS *bool `default:"false" json:"useRoundRobinDns"`
	// Disable collector event time filtering when a date range is specified
	DisableTimeFilter *bool `default:"true" json:"disableTimeFilter"`
	// Reject certificates that cannot be verified against a valid CA (such as self-signed certificates)
	RejectUnauthorized *bool `default:"false" json:"rejectUnauthorized"`
	// Escape characters (\") in search queries will be passed directly to Splunk
	HandleEscapedChars *bool             `default:"false" json:"handleEscapedChars"`
	RetryRules         *RetryRulesSplunk `json:"retryRules,omitempty"`
	Username           *string           `json:"username,omitempty"`
	Password           *string           `json:"password,omitempty"`
	// Select or create a stored secret that references your login credentials
	CredentialsSecret *string `json:"credentialsSecret,omitempty"`
	Token             *string `json:"token,omitempty"`
	// Select or create a stored secret that references your Bearer token
	TokenSecret *string `json:"tokenSecret,omitempty"`
	// URL to use for login API call, this call is expected to be a POST.
	LoginURL *string `default:"https://localhost:9000/api/v1/auth/login" json:"loginUrl"`
	// Template for POST body to send with login request, ${username} and ${password} are used to specify location of these attributes in the message
	LoginBody *string `default:"{ \"username\": \"\\${username}\", \"password\": \"\\${password}\" }" json:"loginBody"`
	// Path to token attribute in login response body. Nested attributes are allowed.
	TokenRespAttribute *string `default:"token" json:"tokenRespAttribute"`
	// JavaScript expression to compute the Authorization header to pass in discover and collect calls. The value ${token} is used to reference the token obtained from login.
	AuthHeaderExpr *string `default:"Bearer \\${token}" json:"authHeaderExpr"`
}

func (c CollectorSplunkCollectorHealthCheckPart0Type) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"type", "search"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetAuthentication() *AuthenticationSplunk {
	if c == nil {
		return nil
	}
	return c.Authentication
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetType() CollectorSplunkType1 {
	if c == nil {
		return CollectorSplunkType1("")
	}
	return c.Type
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetSearchHead() *string {
	if c == nil {
		return nil
	}
	return c.SearchHead
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetSearch() string {
	if c == nil {
		return ""
	}
	return c.Search
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetEarliest() *string {
	if c == nil {
		return nil
	}
	return c.Earliest
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetLatest() *string {
	if c == nil {
		return nil
	}
	return c.Latest
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.Endpoint
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetOutputMode() *OutputModeOptions {
	if c == nil {
		return nil
	}
	return c.OutputMode
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetCollectRequestParams() []CollectRequestParamSplunk {
	if c == nil {
		return nil
	}
	return c.CollectRequestParams
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetCollectRequestHeaders() []CollectRequestHeaderSplunk {
	if c == nil {
		return nil
	}
	return c.CollectRequestHeaders
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetTimeout() *float64 {
	if c == nil {
		return nil
	}
	return c.Timeout
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetUseRoundRobinDNS() *bool {
	if c == nil {
		return nil
	}
	return c.UseRoundRobinDNS
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetDisableTimeFilter() *bool {
	if c == nil {
		return nil
	}
	return c.DisableTimeFilter
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetRejectUnauthorized() *bool {
	if c == nil {
		return nil
	}
	return c.RejectUnauthorized
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetHandleEscapedChars() *bool {
	if c == nil {
		return nil
	}
	return c.HandleEscapedChars
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetRetryRules() *RetryRulesSplunk {
	if c == nil {
		return nil
	}
	return c.RetryRules
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetUsername() *string {
	if c == nil {
		return nil
	}
	return c.Username
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetPassword() *string {
	if c == nil {
		return nil
	}
	return c.Password
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetCredentialsSecret() *string {
	if c == nil {
		return nil
	}
	return c.CredentialsSecret
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetToken() *string {
	if c == nil {
		return nil
	}
	return c.Token
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetTokenSecret() *string {
	if c == nil {
		return nil
	}
	return c.TokenSecret
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetLoginURL() *string {
	if c == nil {
		return nil
	}
	return c.LoginURL
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetLoginBody() *string {
	if c == nil {
		return nil
	}
	return c.LoginBody
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetTokenRespAttribute() *string {
	if c == nil {
		return nil
	}
	return c.TokenRespAttribute
}

func (c *CollectorSplunkCollectorHealthCheckPart0Type) GetAuthHeaderExpr() *string {
	if c == nil {
		return nil
	}
	return c.AuthHeaderExpr
}

type CollectorSplunkType string

const (
	CollectorSplunkTypeCollectorSplunkCollectorHealthCheckPart0Type CollectorSplunkType = "CollectorSplunk_CollectorHealthCheckPart0Type"
	CollectorSplunkTypeCollectorSplunkCollectorHealthCheckPart1Type CollectorSplunkType = "CollectorSplunk_CollectorHealthCheckPart1Type"
	CollectorSplunkTypeCollectorSplunkCollectorHealthCheckPart2Type CollectorSplunkType = "CollectorSplunk_CollectorHealthCheckPart2Type"
	CollectorSplunkTypeCollectorSplunkSplunk1                       CollectorSplunkType = "CollectorSplunk_Splunk_1"
	CollectorSplunkTypeCollectorSplunkSplunk2                       CollectorSplunkType = "CollectorSplunk_Splunk_2"
	CollectorSplunkTypeCollectorSplunkSplunk3                       CollectorSplunkType = "CollectorSplunk_Splunk_3"
	CollectorSplunkTypeCollectorSplunkSplunk4                       CollectorSplunkType = "CollectorSplunk_Splunk_4"
)

type CollectorSplunk struct {
	CollectorSplunkCollectorHealthCheckPart0Type *CollectorSplunkCollectorHealthCheckPart0Type `queryParam:"inline,name=CollectorSplunk" union:"member"`
	CollectorSplunkCollectorHealthCheckPart1Type *CollectorSplunkCollectorHealthCheckPart1Type `queryParam:"inline,name=CollectorSplunk" union:"member"`
	CollectorSplunkCollectorHealthCheckPart2Type *CollectorSplunkCollectorHealthCheckPart2Type `queryParam:"inline,name=CollectorSplunk" union:"member"`
	CollectorSplunkSplunk1                       *CollectorSplunkSplunk1                       `queryParam:"inline,name=CollectorSplunk" union:"member"`
	CollectorSplunkSplunk2                       *CollectorSplunkSplunk2                       `queryParam:"inline,name=CollectorSplunk" union:"member"`
	CollectorSplunkSplunk3                       *CollectorSplunkSplunk3                       `queryParam:"inline,name=CollectorSplunk" union:"member"`
	CollectorSplunkSplunk4                       *CollectorSplunkSplunk4                       `queryParam:"inline,name=CollectorSplunk" union:"member"`

	Type CollectorSplunkType
}

func CreateCollectorSplunkCollectorSplunkCollectorHealthCheckPart0Type(collectorSplunkCollectorHealthCheckPart0Type CollectorSplunkCollectorHealthCheckPart0Type) CollectorSplunk {
	typ := CollectorSplunkTypeCollectorSplunkCollectorHealthCheckPart0Type

	return CollectorSplunk{
		CollectorSplunkCollectorHealthCheckPart0Type: &collectorSplunkCollectorHealthCheckPart0Type,
		Type: typ,
	}
}

func CreateCollectorSplunkCollectorSplunkCollectorHealthCheckPart1Type(collectorSplunkCollectorHealthCheckPart1Type CollectorSplunkCollectorHealthCheckPart1Type) CollectorSplunk {
	typ := CollectorSplunkTypeCollectorSplunkCollectorHealthCheckPart1Type

	return CollectorSplunk{
		CollectorSplunkCollectorHealthCheckPart1Type: &collectorSplunkCollectorHealthCheckPart1Type,
		Type: typ,
	}
}

func CreateCollectorSplunkCollectorSplunkCollectorHealthCheckPart2Type(collectorSplunkCollectorHealthCheckPart2Type CollectorSplunkCollectorHealthCheckPart2Type) CollectorSplunk {
	typ := CollectorSplunkTypeCollectorSplunkCollectorHealthCheckPart2Type

	return CollectorSplunk{
		CollectorSplunkCollectorHealthCheckPart2Type: &collectorSplunkCollectorHealthCheckPart2Type,
		Type: typ,
	}
}

func CreateCollectorSplunkCollectorSplunkSplunk1(collectorSplunkSplunk1 CollectorSplunkSplunk1) CollectorSplunk {
	typ := CollectorSplunkTypeCollectorSplunkSplunk1

	return CollectorSplunk{
		CollectorSplunkSplunk1: &collectorSplunkSplunk1,
		Type:                   typ,
	}
}

func CreateCollectorSplunkCollectorSplunkSplunk2(collectorSplunkSplunk2 CollectorSplunkSplunk2) CollectorSplunk {
	typ := CollectorSplunkTypeCollectorSplunkSplunk2

	return CollectorSplunk{
		CollectorSplunkSplunk2: &collectorSplunkSplunk2,
		Type:                   typ,
	}
}

func CreateCollectorSplunkCollectorSplunkSplunk3(collectorSplunkSplunk3 CollectorSplunkSplunk3) CollectorSplunk {
	typ := CollectorSplunkTypeCollectorSplunkSplunk3

	return CollectorSplunk{
		CollectorSplunkSplunk3: &collectorSplunkSplunk3,
		Type:                   typ,
	}
}

func CreateCollectorSplunkCollectorSplunkSplunk4(collectorSplunkSplunk4 CollectorSplunkSplunk4) CollectorSplunk {
	typ := CollectorSplunkTypeCollectorSplunkSplunk4

	return CollectorSplunk{
		CollectorSplunkSplunk4: &collectorSplunkSplunk4,
		Type:                   typ,
	}
}

func (u *CollectorSplunk) UnmarshalJSON(data []byte) error {

	var collectorSplunkCollectorHealthCheckPart1Type CollectorSplunkCollectorHealthCheckPart1Type = CollectorSplunkCollectorHealthCheckPart1Type{}
	if err := utils.UnmarshalJSON(data, &collectorSplunkCollectorHealthCheckPart1Type, "", true, nil); err == nil {
		u.CollectorSplunkCollectorHealthCheckPart1Type = &collectorSplunkCollectorHealthCheckPart1Type
		u.Type = CollectorSplunkTypeCollectorSplunkCollectorHealthCheckPart1Type
		return nil
	}

	var collectorSplunkSplunk3 CollectorSplunkSplunk3 = CollectorSplunkSplunk3{}
	if err := utils.UnmarshalJSON(data, &collectorSplunkSplunk3, "", true, nil); err == nil {
		u.CollectorSplunkSplunk3 = &collectorSplunkSplunk3
		u.Type = CollectorSplunkTypeCollectorSplunkSplunk3
		return nil
	}

	var collectorSplunkCollectorHealthCheckPart2Type CollectorSplunkCollectorHealthCheckPart2Type = CollectorSplunkCollectorHealthCheckPart2Type{}
	if err := utils.UnmarshalJSON(data, &collectorSplunkCollectorHealthCheckPart2Type, "", true, nil); err == nil {
		u.CollectorSplunkCollectorHealthCheckPart2Type = &collectorSplunkCollectorHealthCheckPart2Type
		u.Type = CollectorSplunkTypeCollectorSplunkCollectorHealthCheckPart2Type
		return nil
	}

	var collectorSplunkSplunk1 CollectorSplunkSplunk1 = CollectorSplunkSplunk1{}
	if err := utils.UnmarshalJSON(data, &collectorSplunkSplunk1, "", true, nil); err == nil {
		u.CollectorSplunkSplunk1 = &collectorSplunkSplunk1
		u.Type = CollectorSplunkTypeCollectorSplunkSplunk1
		return nil
	}

	var collectorSplunkSplunk2 CollectorSplunkSplunk2 = CollectorSplunkSplunk2{}
	if err := utils.UnmarshalJSON(data, &collectorSplunkSplunk2, "", true, nil); err == nil {
		u.CollectorSplunkSplunk2 = &collectorSplunkSplunk2
		u.Type = CollectorSplunkTypeCollectorSplunkSplunk2
		return nil
	}

	var collectorSplunkSplunk4 CollectorSplunkSplunk4 = CollectorSplunkSplunk4{}
	if err := utils.UnmarshalJSON(data, &collectorSplunkSplunk4, "", true, nil); err == nil {
		u.CollectorSplunkSplunk4 = &collectorSplunkSplunk4
		u.Type = CollectorSplunkTypeCollectorSplunkSplunk4
		return nil
	}

	var collectorSplunkCollectorHealthCheckPart0Type CollectorSplunkCollectorHealthCheckPart0Type = CollectorSplunkCollectorHealthCheckPart0Type{}
	if err := utils.UnmarshalJSON(data, &collectorSplunkCollectorHealthCheckPart0Type, "", true, nil); err == nil {
		u.CollectorSplunkCollectorHealthCheckPart0Type = &collectorSplunkCollectorHealthCheckPart0Type
		u.Type = CollectorSplunkTypeCollectorSplunkCollectorHealthCheckPart0Type
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CollectorSplunk", string(data))
}

func (u CollectorSplunk) MarshalJSON() ([]byte, error) {
	if u.CollectorSplunkCollectorHealthCheckPart0Type != nil {
		return utils.MarshalJSON(u.CollectorSplunkCollectorHealthCheckPart0Type, "", true)
	}

	if u.CollectorSplunkCollectorHealthCheckPart1Type != nil {
		return utils.MarshalJSON(u.CollectorSplunkCollectorHealthCheckPart1Type, "", true)
	}

	if u.CollectorSplunkCollectorHealthCheckPart2Type != nil {
		return utils.MarshalJSON(u.CollectorSplunkCollectorHealthCheckPart2Type, "", true)
	}

	if u.CollectorSplunkSplunk1 != nil {
		return utils.MarshalJSON(u.CollectorSplunkSplunk1, "", true)
	}

	if u.CollectorSplunkSplunk2 != nil {
		return utils.MarshalJSON(u.CollectorSplunkSplunk2, "", true)
	}

	if u.CollectorSplunkSplunk3 != nil {
		return utils.MarshalJSON(u.CollectorSplunkSplunk3, "", true)
	}

	if u.CollectorSplunkSplunk4 != nil {
		return utils.MarshalJSON(u.CollectorSplunkSplunk4, "", true)
	}

	return nil, errors.New("could not marshal union type CollectorSplunk: all fields are null")
}
