// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type ConnectionConfInputCollection struct {
	// Pipeline or Pack to process data before sending to the Destination.
	Pipeline *string `json:"pipeline,omitzero"`
	// Destination to send data to when not using Routes.
	Output *string `json:"output,omitzero"`
}

func (c ConnectionConfInputCollection) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConnectionConfInputCollection) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConnectionConfInputCollection) GetPipeline() *string {
	if c == nil {
		return nil
	}
	return c.Pipeline
}

func (c *ConnectionConfInputCollection) GetOutput() *string {
	if c == nil {
		return nil
	}
	return c.Output
}
