// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type CountedGitStatusResult struct {
	// number of items present in the items array
	Count *int64            `json:"count,omitzero"`
	Items []GitStatusResult `json:"items,omitzero"`
}

func (c CountedGitStatusResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CountedGitStatusResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CountedGitStatusResult) GetCount() *int64 {
	if c == nil {
		return nil
	}
	return c.Count
}

func (c *CountedGitStatusResult) GetItems() []GitStatusResult {
	if c == nil {
		return nil
	}
	return c.Items
}
