// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CountedListTeamAccessControlList struct {
	// number of items present in the items array
	Count *int64                  `json:"count,omitempty"`
	Items []TeamAccessControlList `json:"items,omitempty"`
}

func (c *CountedListTeamAccessControlList) GetCount() *int64 {
	if c == nil {
		return nil
	}
	return c.Count
}

func (c *CountedListTeamAccessControlList) GetItems() []TeamAccessControlList {
	if c == nil {
		return nil
	}
	return c.Items
}
