// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CountedOutputTestResponse struct {
	// number of items present in the items array
	Count int64 `json:"count"`
	// List of items in this response.
	Items []OutputTestResponse `json:"items"`
}

func (c *CountedOutputTestResponse) GetCount() int64 {
	if c == nil {
		return 0
	}
	return c.Count
}

func (c *CountedOutputTestResponse) GetItems() []OutputTestResponse {
	if c == nil {
		return []OutputTestResponse{}
	}
	return c.Items
}
