// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DatasetMetadataRunInfo struct {
	// Timestamp (in Unix time) for the earliest event that was observed during the scan (seconds).
	EarliestScannedTime *int64 `json:"earliestScannedTime,omitzero"`
	// Timestamp (in Unix time) when the acceleration run finished (milliseconds).
	FinishedAt *int64 `json:"finishedAt,omitzero"`
	// Timestamp (in Unix time) for the latest event that was observed during the scan (seconds).
	LatestScannedTime *int64 `json:"latestScannedTime,omitzero"`
	// Number of objects on the acceleration manifest after the scan completed.
	ObjectCount *int64 `json:"objectCount,omitzero"`
}

func (d *DatasetMetadataRunInfo) GetEarliestScannedTime() *int64 {
	if d == nil {
		return nil
	}
	return d.EarliestScannedTime
}

func (d *DatasetMetadataRunInfo) GetFinishedAt() *int64 {
	if d == nil {
		return nil
	}
	return d.FinishedAt
}

func (d *DatasetMetadataRunInfo) GetLatestScannedTime() *int64 {
	if d == nil {
		return nil
	}
	return d.LatestScannedTime
}

func (d *DatasetMetadataRunInfo) GetObjectCount() *int64 {
	if d == nil {
		return nil
	}
	return d.ObjectCount
}
