// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DestinationType string

const (
	DestinationTypeDefault                DestinationType = "default"
	DestinationTypeRouter                 DestinationType = "router"
	DestinationTypeTcpjson                DestinationType = "tcpjson"
	DestinationTypeSplunk                 DestinationType = "splunk"
	DestinationTypeSplunkLb               DestinationType = "splunk_lb"
	DestinationTypeSplunkHec              DestinationType = "splunk_hec"
	DestinationTypeSyslog                 DestinationType = "syslog"
	DestinationTypeFilesystem             DestinationType = "filesystem"
	DestinationTypeS3                     DestinationType = "s3"
	DestinationTypeAzureBlob              DestinationType = "azure_blob"
	DestinationTypeAzureDataExplorer      DestinationType = "azure_data_explorer"
	DestinationTypeSentinel               DestinationType = "sentinel"
	DestinationTypeAzureLogs              DestinationType = "azure_logs"
	DestinationTypeKafka                  DestinationType = "kafka"
	DestinationTypeConfluentCloud         DestinationType = "confluent_cloud"
	DestinationTypeMsk                    DestinationType = "msk"
	DestinationTypeKinesis                DestinationType = "kinesis"
	DestinationTypeElastic                DestinationType = "elastic"
	DestinationTypeElasticCloud           DestinationType = "elastic_cloud"
	DestinationTypeMicrosoftFabric        DestinationType = "microsoft_fabric"
	DestinationTypeCloudflareR2           DestinationType = "cloudflare_r2"
	DestinationTypeHoneycomb              DestinationType = "honeycomb"
	DestinationTypeNewrelic               DestinationType = "newrelic"
	DestinationTypeNewrelicEvents         DestinationType = "newrelic_events"
	DestinationTypeSnmp                   DestinationType = "snmp"
	DestinationTypeInfluxdb               DestinationType = "influxdb"
	DestinationTypeMinio                  DestinationType = "minio"
	DestinationTypeDevnull                DestinationType = "devnull"
	DestinationTypeCloudwatch             DestinationType = "cloudwatch"
	DestinationTypeAzureEventhub          DestinationType = "azure_eventhub"
	DestinationTypeStatsd                 DestinationType = "statsd"
	DestinationTypeStatsdExt              DestinationType = "statsd_ext"
	DestinationTypeGraphite               DestinationType = "graphite"
	DestinationTypeWavefront              DestinationType = "wavefront"
	DestinationTypeSignalfx               DestinationType = "signalfx"
	DestinationTypeSqs                    DestinationType = "sqs"
	DestinationTypeGoogleCloudStorage     DestinationType = "google_cloud_storage"
	DestinationTypeSumoLogic              DestinationType = "sumo_logic"
	DestinationTypeDatadog                DestinationType = "datadog"
	DestinationTypeWebhook                DestinationType = "webhook"
	DestinationTypePrometheus             DestinationType = "prometheus"
	DestinationTypeGooglePubsub           DestinationType = "google_pubsub"
	DestinationTypeGoogleChronicle        DestinationType = "google_chronicle"
	DestinationTypeChronicle              DestinationType = "chronicle"
	DestinationTypeGrafanaCloud           DestinationType = "grafana_cloud"
	DestinationTypeLoki                   DestinationType = "loki"
	DestinationTypeOpenTelemetry          DestinationType = "open_telemetry"
	DestinationTypeServiceNow             DestinationType = "service_now"
	DestinationTypeDynatraceOtlp          DestinationType = "dynatrace_otlp"
	DestinationTypeSentinelOneAiSiem      DestinationType = "sentinel_one_ai_siem"
	DestinationTypeDataset                DestinationType = "dataset"
	DestinationTypeRing                   DestinationType = "ring"
	DestinationTypeHumioHec               DestinationType = "humio_hec"
	DestinationTypeCrowdstrikeNextGenSiem DestinationType = "crowdstrike_next_gen_siem"
	DestinationTypeCriblHTTP              DestinationType = "cribl_http"
	DestinationTypeCriblTCP               DestinationType = "cribl_tcp"
	DestinationTypeCriblSearchEngine      DestinationType = "cribl_search_engine"
	DestinationTypeGoogleCloudLogging     DestinationType = "google_cloud_logging"
	DestinationTypeSns                    DestinationType = "sns"
	DestinationTypeDlS3                   DestinationType = "dl_s3"
	DestinationTypeSecurityLake           DestinationType = "security_lake"
	DestinationTypeCriblLake              DestinationType = "cribl_lake"
	DestinationTypeExabeam                DestinationType = "exabeam"
	DestinationTypeDiskSpool              DestinationType = "disk_spool"
	DestinationTypeClickHouse             DestinationType = "click_house"
	DestinationTypeLocalSearchStorage     DestinationType = "local_search_storage"
	DestinationTypeXsiam                  DestinationType = "xsiam"
	DestinationTypeNetflow                DestinationType = "netflow"
	DestinationTypeDynatraceHTTP          DestinationType = "dynatrace_http"
	DestinationTypeDatabricks             DestinationType = "databricks"
	DestinationTypeWizHec                 DestinationType = "wiz_hec"
)

func (e DestinationType) ToPointer() *DestinationType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DestinationType) IsExact() bool {
	if e != nil {
		switch *e {
		case "default", "router", "tcpjson", "splunk", "splunk_lb", "splunk_hec", "syslog", "filesystem", "s3", "azure_blob", "azure_data_explorer", "sentinel", "azure_logs", "kafka", "confluent_cloud", "msk", "kinesis", "elastic", "elastic_cloud", "microsoft_fabric", "cloudflare_r2", "honeycomb", "newrelic", "newrelic_events", "snmp", "influxdb", "minio", "devnull", "cloudwatch", "azure_eventhub", "statsd", "statsd_ext", "graphite", "wavefront", "signalfx", "sqs", "google_cloud_storage", "sumo_logic", "datadog", "webhook", "prometheus", "google_pubsub", "google_chronicle", "chronicle", "grafana_cloud", "loki", "open_telemetry", "service_now", "dynatrace_otlp", "sentinel_one_ai_siem", "dataset", "ring", "humio_hec", "crowdstrike_next_gen_siem", "cribl_http", "cribl_tcp", "cribl_search_engine", "google_cloud_logging", "sns", "dl_s3", "security_lake", "cribl_lake", "exabeam", "disk_spool", "click_house", "local_search_storage", "xsiam", "netflow", "dynatrace_http", "databricks", "wiz_hec":
			return true
		}
	}
	return false
}
