// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type LinesType string

const (
	LinesTypeDiffLineDelete  LinesType = "DiffLineDelete"
	LinesTypeDiffLineInsert  LinesType = "DiffLineInsert"
	LinesTypeDiffLineContext LinesType = "DiffLineContext"
)

// Lines - Diff Line
type Lines struct {
	DiffLineDelete  *DiffLineDelete  `queryParam:"inline,name=lines"`
	DiffLineInsert  *DiffLineInsert  `queryParam:"inline,name=lines"`
	DiffLineContext *DiffLineContext `queryParam:"inline,name=lines"`

	Type LinesType
}

func CreateLinesDiffLineDelete(diffLineDelete DiffLineDelete) Lines {
	typ := LinesTypeDiffLineDelete

	return Lines{
		DiffLineDelete: &diffLineDelete,
		Type:           typ,
	}
}

func CreateLinesDiffLineInsert(diffLineInsert DiffLineInsert) Lines {
	typ := LinesTypeDiffLineInsert

	return Lines{
		DiffLineInsert: &diffLineInsert,
		Type:           typ,
	}
}

func CreateLinesDiffLineContext(diffLineContext DiffLineContext) Lines {
	typ := LinesTypeDiffLineContext

	return Lines{
		DiffLineContext: &diffLineContext,
		Type:            typ,
	}
}

func (u *Lines) UnmarshalJSON(data []byte) error {

	var diffLineDelete DiffLineDelete = DiffLineDelete{}
	if err := utils.UnmarshalJSON(data, &diffLineDelete, "", true, nil); err == nil {
		u.DiffLineDelete = &diffLineDelete
		u.Type = LinesTypeDiffLineDelete
		return nil
	}

	var diffLineInsert DiffLineInsert = DiffLineInsert{}
	if err := utils.UnmarshalJSON(data, &diffLineInsert, "", true, nil); err == nil {
		u.DiffLineInsert = &diffLineInsert
		u.Type = LinesTypeDiffLineInsert
		return nil
	}

	var diffLineContext DiffLineContext = DiffLineContext{}
	if err := utils.UnmarshalJSON(data, &diffLineContext, "", true, nil); err == nil {
		u.DiffLineContext = &diffLineContext
		u.Type = LinesTypeDiffLineContext
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Lines", string(data))
}

func (u Lines) MarshalJSON() ([]byte, error) {
	if u.DiffLineDelete != nil {
		return utils.MarshalJSON(u.DiffLineDelete, "", true)
	}

	if u.DiffLineInsert != nil {
		return utils.MarshalJSON(u.DiffLineInsert, "", true)
	}

	if u.DiffLineContext != nil {
		return utils.MarshalJSON(u.DiffLineContext, "", true)
	}

	return nil, errors.New("could not marshal union type Lines: all fields are null")
}

type Block struct {
	Header string `json:"header"`
	// Diff Line
	Lines         Lines    `json:"lines"`
	NewStartLine  float64  `json:"newStartLine"`
	OldStartLine  float64  `json:"oldStartLine"`
	OldStartLine2 *float64 `json:"oldStartLine2,omitempty"`
}

func (b *Block) GetHeader() string {
	if b == nil {
		return ""
	}
	return b.Header
}

func (b *Block) GetLines() Lines {
	if b == nil {
		return Lines{}
	}
	return b.Lines
}

func (b *Block) GetNewStartLine() float64 {
	if b == nil {
		return 0.0
	}
	return b.NewStartLine
}

func (b *Block) GetOldStartLine() float64 {
	if b == nil {
		return 0.0
	}
	return b.OldStartLine
}

func (b *Block) GetOldStartLine2() *float64 {
	if b == nil {
		return nil
	}
	return b.OldStartLine2
}

type ChecksumBeforeType string

const (
	ChecksumBeforeTypeStr        ChecksumBeforeType = "str"
	ChecksumBeforeTypeArrayOfStr ChecksumBeforeType = "arrayOfStr"
)

type ChecksumBefore struct {
	Str        *string  `queryParam:"inline,name=checksumBefore"`
	ArrayOfStr []string `queryParam:"inline,name=checksumBefore"`

	Type ChecksumBeforeType
}

func CreateChecksumBeforeStr(str string) ChecksumBefore {
	typ := ChecksumBeforeTypeStr

	return ChecksumBefore{
		Str:  &str,
		Type: typ,
	}
}

func CreateChecksumBeforeArrayOfStr(arrayOfStr []string) ChecksumBefore {
	typ := ChecksumBeforeTypeArrayOfStr

	return ChecksumBefore{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *ChecksumBefore) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = ChecksumBeforeTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = ChecksumBeforeTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChecksumBefore", string(data))
}

func (u ChecksumBefore) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type ChecksumBefore: all fields are null")
}

type OldModeType string

const (
	OldModeTypeStr        OldModeType = "str"
	OldModeTypeArrayOfStr OldModeType = "arrayOfStr"
)

type OldMode struct {
	Str        *string  `queryParam:"inline,name=oldMode"`
	ArrayOfStr []string `queryParam:"inline,name=oldMode"`

	Type OldModeType
}

func CreateOldModeStr(str string) OldMode {
	typ := OldModeTypeStr

	return OldMode{
		Str:  &str,
		Type: typ,
	}
}

func CreateOldModeArrayOfStr(arrayOfStr []string) OldMode {
	typ := OldModeTypeArrayOfStr

	return OldMode{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *OldMode) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = OldModeTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = OldModeTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for OldMode", string(data))
}

func (u OldMode) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type OldMode: all fields are null")
}

type DiffFiles struct {
	AddedLines          float64         `json:"addedLines"`
	Blocks              []Block         `json:"blocks"`
	ChangedPercentage   *float64        `json:"changedPercentage,omitempty"`
	ChecksumAfter       *string         `json:"checksumAfter,omitempty"`
	ChecksumBefore      *ChecksumBefore `json:"checksumBefore,omitempty"`
	DeletedFileMode     *string         `json:"deletedFileMode,omitempty"`
	DeletedLines        float64         `json:"deletedLines"`
	IsBinary            *bool           `json:"isBinary,omitempty"`
	IsCombined          bool            `json:"isCombined"`
	IsCopy              *bool           `json:"isCopy,omitempty"`
	IsDeleted           *bool           `json:"isDeleted,omitempty"`
	IsGitDiff           bool            `json:"isGitDiff"`
	IsNew               *bool           `json:"isNew,omitempty"`
	IsRename            *bool           `json:"isRename,omitempty"`
	IsTooBig            *bool           `json:"isTooBig,omitempty"`
	Language            string          `json:"language"`
	Mode                *string         `json:"mode,omitempty"`
	NewFileMode         *string         `json:"newFileMode,omitempty"`
	NewMode             *string         `json:"newMode,omitempty"`
	NewName             string          `json:"newName"`
	OldMode             *OldMode        `json:"oldMode,omitempty"`
	OldName             string          `json:"oldName"`
	UnchangedPercentage *float64        `json:"unchangedPercentage,omitempty"`
}

func (d *DiffFiles) GetAddedLines() float64 {
	if d == nil {
		return 0.0
	}
	return d.AddedLines
}

func (d *DiffFiles) GetBlocks() []Block {
	if d == nil {
		return []Block{}
	}
	return d.Blocks
}

func (d *DiffFiles) GetChangedPercentage() *float64 {
	if d == nil {
		return nil
	}
	return d.ChangedPercentage
}

func (d *DiffFiles) GetChecksumAfter() *string {
	if d == nil {
		return nil
	}
	return d.ChecksumAfter
}

func (d *DiffFiles) GetChecksumBefore() *ChecksumBefore {
	if d == nil {
		return nil
	}
	return d.ChecksumBefore
}

func (d *DiffFiles) GetDeletedFileMode() *string {
	if d == nil {
		return nil
	}
	return d.DeletedFileMode
}

func (d *DiffFiles) GetDeletedLines() float64 {
	if d == nil {
		return 0.0
	}
	return d.DeletedLines
}

func (d *DiffFiles) GetIsBinary() *bool {
	if d == nil {
		return nil
	}
	return d.IsBinary
}

func (d *DiffFiles) GetIsCombined() bool {
	if d == nil {
		return false
	}
	return d.IsCombined
}

func (d *DiffFiles) GetIsCopy() *bool {
	if d == nil {
		return nil
	}
	return d.IsCopy
}

func (d *DiffFiles) GetIsDeleted() *bool {
	if d == nil {
		return nil
	}
	return d.IsDeleted
}

func (d *DiffFiles) GetIsGitDiff() bool {
	if d == nil {
		return false
	}
	return d.IsGitDiff
}

func (d *DiffFiles) GetIsNew() *bool {
	if d == nil {
		return nil
	}
	return d.IsNew
}

func (d *DiffFiles) GetIsRename() *bool {
	if d == nil {
		return nil
	}
	return d.IsRename
}

func (d *DiffFiles) GetIsTooBig() *bool {
	if d == nil {
		return nil
	}
	return d.IsTooBig
}

func (d *DiffFiles) GetLanguage() string {
	if d == nil {
		return ""
	}
	return d.Language
}

func (d *DiffFiles) GetMode() *string {
	if d == nil {
		return nil
	}
	return d.Mode
}

func (d *DiffFiles) GetNewFileMode() *string {
	if d == nil {
		return nil
	}
	return d.NewFileMode
}

func (d *DiffFiles) GetNewMode() *string {
	if d == nil {
		return nil
	}
	return d.NewMode
}

func (d *DiffFiles) GetNewName() string {
	if d == nil {
		return ""
	}
	return d.NewName
}

func (d *DiffFiles) GetOldMode() *OldMode {
	if d == nil {
		return nil
	}
	return d.OldMode
}

func (d *DiffFiles) GetOldName() string {
	if d == nil {
		return ""
	}
	return d.OldName
}

func (d *DiffFiles) GetUnchangedPercentage() *float64 {
	if d == nil {
		return nil
	}
	return d.UnchangedPercentage
}
