// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type FunctionPublishMetricsID string

const (
	FunctionPublishMetricsIDPublishMetrics FunctionPublishMetricsID = "publish_metrics"
)

func (e FunctionPublishMetricsID) ToPointer() *FunctionPublishMetricsID {
	return &e
}
func (e *FunctionPublishMetricsID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "publish_metrics":
		*e = FunctionPublishMetricsID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FunctionPublishMetricsID: %v", v)
	}
}

type FunctionPublishMetrics struct {
	Filename      string                   `json:"__filename"`
	AsyncTimeout  *float64                 `json:"asyncTimeout,omitempty"`
	CriblVersion  *string                  `json:"cribl_version,omitempty"`
	Disabled      *bool                    `json:"disabled,omitempty"`
	Group         string                   `json:"group"`
	HandleSignals *bool                    `json:"handleSignals,omitempty"`
	ID            FunctionPublishMetricsID `json:"id"`
	LoadTime      float64                  `json:"loadTime"`
	ModTime       float64                  `json:"modTime"`
	Name          string                   `json:"name"`
	Sync          *bool                    `json:"sync,omitempty"`
	Uischema      map[string]any           `json:"uischema"`
	Version       string                   `json:"version"`
	Schema        map[string]any           `json:"schema,omitempty"`
}

func (f FunctionPublishMetrics) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionPublishMetrics) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionPublishMetrics) GetFilename() string {
	if f == nil {
		return ""
	}
	return f.Filename
}

func (f *FunctionPublishMetrics) GetAsyncTimeout() *float64 {
	if f == nil {
		return nil
	}
	return f.AsyncTimeout
}

func (f *FunctionPublishMetrics) GetCriblVersion() *string {
	if f == nil {
		return nil
	}
	return f.CriblVersion
}

func (f *FunctionPublishMetrics) GetDisabled() *bool {
	if f == nil {
		return nil
	}
	return f.Disabled
}

func (f *FunctionPublishMetrics) GetGroup() string {
	if f == nil {
		return ""
	}
	return f.Group
}

func (f *FunctionPublishMetrics) GetHandleSignals() *bool {
	if f == nil {
		return nil
	}
	return f.HandleSignals
}

func (f *FunctionPublishMetrics) GetID() FunctionPublishMetricsID {
	if f == nil {
		return FunctionPublishMetricsID("")
	}
	return f.ID
}

func (f *FunctionPublishMetrics) GetLoadTime() float64 {
	if f == nil {
		return 0.0
	}
	return f.LoadTime
}

func (f *FunctionPublishMetrics) GetModTime() float64 {
	if f == nil {
		return 0.0
	}
	return f.ModTime
}

func (f *FunctionPublishMetrics) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FunctionPublishMetrics) GetSync() *bool {
	if f == nil {
		return nil
	}
	return f.Sync
}

func (f *FunctionPublishMetrics) GetUischema() map[string]any {
	if f == nil {
		return map[string]any{}
	}
	return f.Uischema
}

func (f *FunctionPublishMetrics) GetVersion() string {
	if f == nil {
		return ""
	}
	return f.Version
}

func (f *FunctionPublishMetrics) GetSchema() map[string]any {
	if f == nil {
		return nil
	}
	return f.Schema
}
