// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

// FunctionLocalSearchDatatypeParserID - Identifier of the Function. Always <code>local_search_datatype_parser</code>
type FunctionLocalSearchDatatypeParserID string

const (
	FunctionLocalSearchDatatypeParserIDLocalSearchDatatypeParser FunctionLocalSearchDatatypeParserID = "local_search_datatype_parser"
)

func (e FunctionLocalSearchDatatypeParserID) ToPointer() *FunctionLocalSearchDatatypeParserID {
	return &e
}
func (e *FunctionLocalSearchDatatypeParserID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "local_search_datatype_parser":
		*e = FunctionLocalSearchDatatypeParserID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FunctionLocalSearchDatatypeParserID: %v", v)
	}
}

type FunctionLocalSearchDatatypeParser struct {
	// Path to the JavaScript file that implements the Function.
	Filename string `json:"__filename"`
	// Maximum time, in milliseconds, that the Function is allowed to run asynchronously before timing out.
	AsyncTimeout *float64 `json:"asyncTimeout,omitzero"`
	// Minimum Cribl version required by the Function, if applicable.
	CriblVersion *string `json:"cribl_version,omitzero"`
	// If <code>true</code>, the Function is disabled and will not execute in a Pipeline. Otherwise, <code>false</code>.
	Disabled *bool `json:"disabled,omitzero"`
	// Category group the Function belongs to.
	Group string `json:"group"`
	// If <code>true</code>, the Function handles stream signals such as <code>flush</code> and <code>close</code>. Otherwise, <code>false</code>.
	HandleSignals *bool `json:"handleSignals,omitzero"`
	// Identifier of the Function. Always <code>local_search_datatype_parser</code>
	ID FunctionLocalSearchDatatypeParserID `json:"id"`
	// Time the Function module was loaded, in milliseconds since the Unix epoch.
	LoadTime float64 `json:"loadTime"`
	// Time the Function module was last modified, in milliseconds since the Unix epoch.
	ModTime float64 `json:"modTime"`
	// Display name of the Function.
	Name string `json:"name"`
	// If <code>true</code>, the Function executes synchronously. Otherwise, <code>false</code>.
	Sync *bool `json:"sync,omitzero"`
	// UI Schema that controls how the Function's configuration form is rendered.
	Uischema map[string]any `json:"uischema"`
	// Version string of the Function.
	Version string `json:"version"`
	// JSON Schema document that describes the Function configuration.
	Schema map[string]any `json:"schema,omitzero"`
}

func (f FunctionLocalSearchDatatypeParser) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionLocalSearchDatatypeParser) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionLocalSearchDatatypeParser) GetFilename() string {
	if f == nil {
		return ""
	}
	return f.Filename
}

func (f *FunctionLocalSearchDatatypeParser) GetAsyncTimeout() *float64 {
	if f == nil {
		return nil
	}
	return f.AsyncTimeout
}

func (f *FunctionLocalSearchDatatypeParser) GetCriblVersion() *string {
	if f == nil {
		return nil
	}
	return f.CriblVersion
}

func (f *FunctionLocalSearchDatatypeParser) GetDisabled() *bool {
	if f == nil {
		return nil
	}
	return f.Disabled
}

func (f *FunctionLocalSearchDatatypeParser) GetGroup() string {
	if f == nil {
		return ""
	}
	return f.Group
}

func (f *FunctionLocalSearchDatatypeParser) GetHandleSignals() *bool {
	if f == nil {
		return nil
	}
	return f.HandleSignals
}

func (f *FunctionLocalSearchDatatypeParser) GetID() FunctionLocalSearchDatatypeParserID {
	if f == nil {
		return FunctionLocalSearchDatatypeParserID("")
	}
	return f.ID
}

func (f *FunctionLocalSearchDatatypeParser) GetLoadTime() float64 {
	if f == nil {
		return 0.0
	}
	return f.LoadTime
}

func (f *FunctionLocalSearchDatatypeParser) GetModTime() float64 {
	if f == nil {
		return 0.0
	}
	return f.ModTime
}

func (f *FunctionLocalSearchDatatypeParser) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FunctionLocalSearchDatatypeParser) GetSync() *bool {
	if f == nil {
		return nil
	}
	return f.Sync
}

func (f *FunctionLocalSearchDatatypeParser) GetUischema() map[string]any {
	if f == nil {
		return map[string]any{}
	}
	return f.Uischema
}

func (f *FunctionLocalSearchDatatypeParser) GetVersion() string {
	if f == nil {
		return ""
	}
	return f.Version
}

func (f *FunctionLocalSearchDatatypeParser) GetSchema() map[string]any {
	if f == nil {
		return nil
	}
	return f.Schema
}
