// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type FunctionUnrollID string

const (
	FunctionUnrollIDUnroll FunctionUnrollID = "unroll"
)

func (e FunctionUnrollID) ToPointer() *FunctionUnrollID {
	return &e
}
func (e *FunctionUnrollID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unroll":
		*e = FunctionUnrollID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FunctionUnrollID: %v", v)
	}
}

type FunctionUnroll struct {
	Filename      string           `json:"__filename"`
	AsyncTimeout  *float64         `json:"asyncTimeout,omitzero"`
	CriblVersion  *string          `json:"cribl_version,omitzero"`
	Disabled      *bool            `json:"disabled,omitzero"`
	Group         string           `json:"group"`
	HandleSignals *bool            `json:"handleSignals,omitzero"`
	ID            FunctionUnrollID `json:"id"`
	LoadTime      float64          `json:"loadTime"`
	ModTime       float64          `json:"modTime"`
	Name          string           `json:"name"`
	Sync          *bool            `json:"sync,omitzero"`
	Uischema      map[string]any   `json:"uischema"`
	Version       string           `json:"version"`
	Schema        map[string]any   `json:"schema,omitzero"`
}

func (f FunctionUnroll) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionUnroll) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionUnroll) GetFilename() string {
	if f == nil {
		return ""
	}
	return f.Filename
}

func (f *FunctionUnroll) GetAsyncTimeout() *float64 {
	if f == nil {
		return nil
	}
	return f.AsyncTimeout
}

func (f *FunctionUnroll) GetCriblVersion() *string {
	if f == nil {
		return nil
	}
	return f.CriblVersion
}

func (f *FunctionUnroll) GetDisabled() *bool {
	if f == nil {
		return nil
	}
	return f.Disabled
}

func (f *FunctionUnroll) GetGroup() string {
	if f == nil {
		return ""
	}
	return f.Group
}

func (f *FunctionUnroll) GetHandleSignals() *bool {
	if f == nil {
		return nil
	}
	return f.HandleSignals
}

func (f *FunctionUnroll) GetID() FunctionUnrollID {
	if f == nil {
		return FunctionUnrollID("")
	}
	return f.ID
}

func (f *FunctionUnroll) GetLoadTime() float64 {
	if f == nil {
		return 0.0
	}
	return f.LoadTime
}

func (f *FunctionUnroll) GetModTime() float64 {
	if f == nil {
		return 0.0
	}
	return f.ModTime
}

func (f *FunctionUnroll) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FunctionUnroll) GetSync() *bool {
	if f == nil {
		return nil
	}
	return f.Sync
}

func (f *FunctionUnroll) GetUischema() map[string]any {
	if f == nil {
		return map[string]any{}
	}
	return f.Uischema
}

func (f *FunctionUnroll) GetVersion() string {
	if f == nil {
		return ""
	}
	return f.Version
}

func (f *FunctionUnroll) GetSchema() map[string]any {
	if f == nil {
		return nil
	}
	return f.Schema
}
