// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type ExistingOrNew string

const (
	// ExistingOrNewExisting Use Existing
	ExistingOrNewExisting ExistingOrNew = "existing"
	// ExistingOrNewNew Create New
	ExistingOrNewNew ExistingOrNew = "new"
)

func (e ExistingOrNew) ToPointer() *ExistingOrNew {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ExistingOrNew) IsExact() bool {
	if e != nil {
		switch *e {
		case "existing", "new":
			return true
		}
	}
	return false
}

type FunctionConfSchemaEventBreaker struct {
	ExistingOrNew *ExistingOrNew `json:"existingOrNew,omitempty"`
	// Add this Function name to the cribl_breaker field
	ShouldMarkCriblBreaker *bool `json:"shouldMarkCriblBreaker,omitempty"`
}

func (f FunctionConfSchemaEventBreaker) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionConfSchemaEventBreaker) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionConfSchemaEventBreaker) GetExistingOrNew() *ExistingOrNew {
	if f == nil {
		return nil
	}
	return f.ExistingOrNew
}

func (f *FunctionConfSchemaEventBreaker) GetShouldMarkCriblBreaker() *bool {
	if f == nil {
		return nil
	}
	return f.ShouldMarkCriblBreaker
}
