// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type FunctionCefID string

const (
	FunctionCefIDCef FunctionCefID = "cef"
)

func (e FunctionCefID) ToPointer() *FunctionCefID {
	return &e
}
func (e *FunctionCefID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cef":
		*e = FunctionCefID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FunctionCefID: %v", v)
	}
}

type FunctionCef struct {
	Filename      string         `json:"__filename"`
	AsyncTimeout  *float64       `json:"asyncTimeout,omitzero"`
	CriblVersion  *string        `json:"cribl_version,omitzero"`
	Disabled      *bool          `json:"disabled,omitzero"`
	Group         string         `json:"group"`
	HandleSignals *bool          `json:"handleSignals,omitzero"`
	ID            FunctionCefID  `json:"id"`
	LoadTime      float64        `json:"loadTime"`
	ModTime       float64        `json:"modTime"`
	Name          string         `json:"name"`
	Sync          *bool          `json:"sync,omitzero"`
	Uischema      map[string]any `json:"uischema"`
	Version       string         `json:"version"`
	Schema        map[string]any `json:"schema,omitzero"`
}

func (f FunctionCef) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionCef) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionCef) GetFilename() string {
	if f == nil {
		return ""
	}
	return f.Filename
}

func (f *FunctionCef) GetAsyncTimeout() *float64 {
	if f == nil {
		return nil
	}
	return f.AsyncTimeout
}

func (f *FunctionCef) GetCriblVersion() *string {
	if f == nil {
		return nil
	}
	return f.CriblVersion
}

func (f *FunctionCef) GetDisabled() *bool {
	if f == nil {
		return nil
	}
	return f.Disabled
}

func (f *FunctionCef) GetGroup() string {
	if f == nil {
		return ""
	}
	return f.Group
}

func (f *FunctionCef) GetHandleSignals() *bool {
	if f == nil {
		return nil
	}
	return f.HandleSignals
}

func (f *FunctionCef) GetID() FunctionCefID {
	if f == nil {
		return FunctionCefID("")
	}
	return f.ID
}

func (f *FunctionCef) GetLoadTime() float64 {
	if f == nil {
		return 0.0
	}
	return f.LoadTime
}

func (f *FunctionCef) GetModTime() float64 {
	if f == nil {
		return 0.0
	}
	return f.ModTime
}

func (f *FunctionCef) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FunctionCef) GetSync() *bool {
	if f == nil {
		return nil
	}
	return f.Sync
}

func (f *FunctionCef) GetUischema() map[string]any {
	if f == nil {
		return map[string]any{}
	}
	return f.Uischema
}

func (f *FunctionCef) GetVersion() string {
	if f == nil {
		return ""
	}
	return f.Version
}

func (f *FunctionCef) GetSchema() map[string]any {
	if f == nil {
		return nil
	}
	return f.Schema
}
