// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type FunctionConfSchemaNotifications struct {
	// Notification ID
	ID *string `json:"id,omitempty"`
	// Notification event state field name
	Field *string `json:"field,omitempty"`
	// Toggle deduplication.
	Deduplicate *bool `json:"deduplicate,omitempty"`
}

func (f FunctionConfSchemaNotifications) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionConfSchemaNotifications) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionConfSchemaNotifications) GetID() *string {
	if f == nil {
		return nil
	}
	return f.ID
}

func (f *FunctionConfSchemaNotifications) GetField() *string {
	if f == nil {
		return nil
	}
	return f.Field
}

func (f *FunctionConfSchemaNotifications) GetDeduplicate() *bool {
	if f == nil {
		return nil
	}
	return f.Deduplicate
}
