// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type InputWizWebhookPqEnabledTrueWithPqConstraint struct {
	// Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers).
	PqEnabled bool    `json:"pqEnabled"`
	Pq        *PqType `json:"pq,omitempty"`
	// Unique ID for this input
	ID       *string             `json:"id,omitempty"`
	Type     InputWizWebhookType `json:"type"`
	Disabled *bool               `json:"disabled,omitempty"`
	// Pipeline to process data from this Source before sending it through the Routes
	Pipeline *string `json:"pipeline,omitempty"`
	// Select whether to send data to Routes, or directly to Destinations.
	SendToRoutes *bool `json:"sendToRoutes,omitempty"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Tags for filtering and grouping in @{product}
	Streamtags []string `json:"streamtags,omitempty"`
	// Direct connections to Destinations, and optionally via a Pipeline or a Pack
	Connections []ItemsTypeConnectionsOptional `json:"connections,omitempty"`
	// Address to bind on. Defaults to 0.0.0.0 (all addresses).
	Host string `json:"host"`
	// Port to listen on
	Port float64 `json:"port"`
	// Shared secrets to be provided by any client (Authorization: <token>). If empty, unauthorized access is permitted.
	AuthTokens []string                   `json:"authTokens,omitempty"`
	TLS        *TLSSettingsServerSideType `json:"tls,omitempty"`
	// Maximum number of active requests allowed per Worker Process. Set to 0 for unlimited. Caution: Increasing the limit above the default value, or setting it to unlimited, may degrade performance and reduce throughput.
	MaxActiveReq *float64 `json:"maxActiveReq,omitempty"`
	// Maximum number of requests per socket before @{product} instructs the client to close the connection. Default is 0 (unlimited).
	MaxRequestsPerSocket *int64 `json:"maxRequestsPerSocket,omitempty"`
	// Extract the client IP and port from PROXY protocol v1/v2. When enabled, the X-Forwarded-For header is ignored. Disable to use the X-Forwarded-For header for client IP extraction.
	EnableProxyHeader *bool `json:"enableProxyHeader,omitempty"`
	// Add request headers to events, in the __headers field
	CaptureHeaders *bool `json:"captureHeaders,omitempty"`
	// How often request activity is logged at the `info` level. A value of 1 would log every request, 10 every 10th request, etc.
	ActivityLogSampleRate *float64 `json:"activityLogSampleRate,omitempty"`
	// How long to wait for an incoming request to complete before aborting it. Use 0 to disable.
	RequestTimeout *float64 `json:"requestTimeout,omitempty"`
	// How long @{product} should wait before assuming that an inactive socket has timed out. To wait forever, set to 0.
	SocketTimeout *float64 `json:"socketTimeout,omitempty"`
	// After the last response is sent, @{product} will wait this long for additional data before closing the socket connection. Minimum 1 second, maximum 600 seconds (10 minutes).
	KeepAliveTimeout *float64 `json:"keepAliveTimeout,omitempty"`
	// Expose the /cribl_health endpoint, which returns 200 OK when this Source is healthy
	EnableHealthCheck *bool `json:"enableHealthCheck,omitempty"`
	// Messages from matched IP addresses will be processed, unless also matched by the denylist
	IPAllowlistRegex *string `json:"ipAllowlistRegex,omitempty"`
	// Messages from matched IP addresses will be ignored. This takes precedence over the allowlist.
	IPDenylistRegex *string `json:"ipDenylistRegex,omitempty"`
	// A list of event-breaking rulesets that will be applied, in order, to the input data stream
	BreakerRulesets []string `json:"breakerRulesets,omitempty"`
	// How long (in milliseconds) the Event Breaker will wait for new data to be sent to a specific channel before flushing the data stream out, as is, to the Pipelines
	StaleChannelFlushMs *float64 `json:"staleChannelFlushMs,omitempty"`
	// Fields to add to events from this input
	Metadata []ItemsTypeNotificationMetadata `json:"metadata,omitempty"`
	// List of URI paths accepted by this input. Wildcards are supported (such as /api/v*/hook). Defaults to allow all.
	AllowedPaths []string `json:"allowedPaths,omitempty"`
	// List of HTTP methods accepted by this input. Wildcards are supported (such as P*, GET). Defaults to allow all.
	AllowedMethods []string `json:"allowedMethods,omitempty"`
	// Shared secrets to be provided by any client (Authorization: <token>). If empty, unauthorized access is permitted.
	AuthTokensExt []ItemsTypeAuthTokensExt `json:"authTokensExt,omitempty"`
	Description   *string                  `json:"description,omitempty"`
}

func (i InputWizWebhookPqEnabledTrueWithPqConstraint) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"pqEnabled", "type", "host", "port"}); err != nil {
		return err
	}
	return nil
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetPqEnabled() bool {
	if i == nil {
		return false
	}
	return i.PqEnabled
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetPq() *PqType {
	if i == nil {
		return nil
	}
	return i.Pq
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetType() InputWizWebhookType {
	if i == nil {
		return InputWizWebhookType("")
	}
	return i.Type
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetDisabled() *bool {
	if i == nil {
		return nil
	}
	return i.Disabled
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetPipeline() *string {
	if i == nil {
		return nil
	}
	return i.Pipeline
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetSendToRoutes() *bool {
	if i == nil {
		return nil
	}
	return i.SendToRoutes
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetEnvironment() *string {
	if i == nil {
		return nil
	}
	return i.Environment
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetStreamtags() []string {
	if i == nil {
		return nil
	}
	return i.Streamtags
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetConnections() []ItemsTypeConnectionsOptional {
	if i == nil {
		return nil
	}
	return i.Connections
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetHost() string {
	if i == nil {
		return ""
	}
	return i.Host
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetPort() float64 {
	if i == nil {
		return 0.0
	}
	return i.Port
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetAuthTokens() []string {
	if i == nil {
		return nil
	}
	return i.AuthTokens
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetTLS() *TLSSettingsServerSideType {
	if i == nil {
		return nil
	}
	return i.TLS
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetMaxActiveReq() *float64 {
	if i == nil {
		return nil
	}
	return i.MaxActiveReq
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetMaxRequestsPerSocket() *int64 {
	if i == nil {
		return nil
	}
	return i.MaxRequestsPerSocket
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetEnableProxyHeader() *bool {
	if i == nil {
		return nil
	}
	return i.EnableProxyHeader
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetCaptureHeaders() *bool {
	if i == nil {
		return nil
	}
	return i.CaptureHeaders
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetActivityLogSampleRate() *float64 {
	if i == nil {
		return nil
	}
	return i.ActivityLogSampleRate
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetRequestTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.RequestTimeout
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetSocketTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.SocketTimeout
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetKeepAliveTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.KeepAliveTimeout
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetEnableHealthCheck() *bool {
	if i == nil {
		return nil
	}
	return i.EnableHealthCheck
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetIPAllowlistRegex() *string {
	if i == nil {
		return nil
	}
	return i.IPAllowlistRegex
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetIPDenylistRegex() *string {
	if i == nil {
		return nil
	}
	return i.IPDenylistRegex
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetBreakerRulesets() []string {
	if i == nil {
		return nil
	}
	return i.BreakerRulesets
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetStaleChannelFlushMs() *float64 {
	if i == nil {
		return nil
	}
	return i.StaleChannelFlushMs
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetMetadata() []ItemsTypeNotificationMetadata {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetAllowedPaths() []string {
	if i == nil {
		return nil
	}
	return i.AllowedPaths
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetAllowedMethods() []string {
	if i == nil {
		return nil
	}
	return i.AllowedMethods
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetAuthTokensExt() []ItemsTypeAuthTokensExt {
	if i == nil {
		return nil
	}
	return i.AuthTokensExt
}

func (i *InputWizWebhookPqEnabledTrueWithPqConstraint) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

type InputWizWebhookPqEnabledFalseConstraint struct {
	// Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers).
	PqEnabled bool `json:"pqEnabled"`
	// Unique ID for this input
	ID       *string             `json:"id,omitempty"`
	Type     InputWizWebhookType `json:"type"`
	Disabled *bool               `json:"disabled,omitempty"`
	// Pipeline to process data from this Source before sending it through the Routes
	Pipeline *string `json:"pipeline,omitempty"`
	// Select whether to send data to Routes, or directly to Destinations.
	SendToRoutes *bool `json:"sendToRoutes,omitempty"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Tags for filtering and grouping in @{product}
	Streamtags []string `json:"streamtags,omitempty"`
	// Direct connections to Destinations, and optionally via a Pipeline or a Pack
	Connections []ItemsTypeConnectionsOptional `json:"connections,omitempty"`
	Pq          *PqType                        `json:"pq,omitempty"`
	// Address to bind on. Defaults to 0.0.0.0 (all addresses).
	Host string `json:"host"`
	// Port to listen on
	Port float64 `json:"port"`
	// Shared secrets to be provided by any client (Authorization: <token>). If empty, unauthorized access is permitted.
	AuthTokens []string                   `json:"authTokens,omitempty"`
	TLS        *TLSSettingsServerSideType `json:"tls,omitempty"`
	// Maximum number of active requests allowed per Worker Process. Set to 0 for unlimited. Caution: Increasing the limit above the default value, or setting it to unlimited, may degrade performance and reduce throughput.
	MaxActiveReq *float64 `json:"maxActiveReq,omitempty"`
	// Maximum number of requests per socket before @{product} instructs the client to close the connection. Default is 0 (unlimited).
	MaxRequestsPerSocket *int64 `json:"maxRequestsPerSocket,omitempty"`
	// Extract the client IP and port from PROXY protocol v1/v2. When enabled, the X-Forwarded-For header is ignored. Disable to use the X-Forwarded-For header for client IP extraction.
	EnableProxyHeader *bool `json:"enableProxyHeader,omitempty"`
	// Add request headers to events, in the __headers field
	CaptureHeaders *bool `json:"captureHeaders,omitempty"`
	// How often request activity is logged at the `info` level. A value of 1 would log every request, 10 every 10th request, etc.
	ActivityLogSampleRate *float64 `json:"activityLogSampleRate,omitempty"`
	// How long to wait for an incoming request to complete before aborting it. Use 0 to disable.
	RequestTimeout *float64 `json:"requestTimeout,omitempty"`
	// How long @{product} should wait before assuming that an inactive socket has timed out. To wait forever, set to 0.
	SocketTimeout *float64 `json:"socketTimeout,omitempty"`
	// After the last response is sent, @{product} will wait this long for additional data before closing the socket connection. Minimum 1 second, maximum 600 seconds (10 minutes).
	KeepAliveTimeout *float64 `json:"keepAliveTimeout,omitempty"`
	// Expose the /cribl_health endpoint, which returns 200 OK when this Source is healthy
	EnableHealthCheck *bool `json:"enableHealthCheck,omitempty"`
	// Messages from matched IP addresses will be processed, unless also matched by the denylist
	IPAllowlistRegex *string `json:"ipAllowlistRegex,omitempty"`
	// Messages from matched IP addresses will be ignored. This takes precedence over the allowlist.
	IPDenylistRegex *string `json:"ipDenylistRegex,omitempty"`
	// A list of event-breaking rulesets that will be applied, in order, to the input data stream
	BreakerRulesets []string `json:"breakerRulesets,omitempty"`
	// How long (in milliseconds) the Event Breaker will wait for new data to be sent to a specific channel before flushing the data stream out, as is, to the Pipelines
	StaleChannelFlushMs *float64 `json:"staleChannelFlushMs,omitempty"`
	// Fields to add to events from this input
	Metadata []ItemsTypeNotificationMetadata `json:"metadata,omitempty"`
	// List of URI paths accepted by this input. Wildcards are supported (such as /api/v*/hook). Defaults to allow all.
	AllowedPaths []string `json:"allowedPaths,omitempty"`
	// List of HTTP methods accepted by this input. Wildcards are supported (such as P*, GET). Defaults to allow all.
	AllowedMethods []string `json:"allowedMethods,omitempty"`
	// Shared secrets to be provided by any client (Authorization: <token>). If empty, unauthorized access is permitted.
	AuthTokensExt []ItemsTypeAuthTokensExt `json:"authTokensExt,omitempty"`
	Description   *string                  `json:"description,omitempty"`
}

func (i InputWizWebhookPqEnabledFalseConstraint) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWizWebhookPqEnabledFalseConstraint) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"pqEnabled", "type", "host", "port"}); err != nil {
		return err
	}
	return nil
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetPqEnabled() bool {
	if i == nil {
		return false
	}
	return i.PqEnabled
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetType() InputWizWebhookType {
	if i == nil {
		return InputWizWebhookType("")
	}
	return i.Type
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetDisabled() *bool {
	if i == nil {
		return nil
	}
	return i.Disabled
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetPipeline() *string {
	if i == nil {
		return nil
	}
	return i.Pipeline
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetSendToRoutes() *bool {
	if i == nil {
		return nil
	}
	return i.SendToRoutes
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetEnvironment() *string {
	if i == nil {
		return nil
	}
	return i.Environment
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetStreamtags() []string {
	if i == nil {
		return nil
	}
	return i.Streamtags
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetConnections() []ItemsTypeConnectionsOptional {
	if i == nil {
		return nil
	}
	return i.Connections
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetPq() *PqType {
	if i == nil {
		return nil
	}
	return i.Pq
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetHost() string {
	if i == nil {
		return ""
	}
	return i.Host
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetPort() float64 {
	if i == nil {
		return 0.0
	}
	return i.Port
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetAuthTokens() []string {
	if i == nil {
		return nil
	}
	return i.AuthTokens
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetTLS() *TLSSettingsServerSideType {
	if i == nil {
		return nil
	}
	return i.TLS
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetMaxActiveReq() *float64 {
	if i == nil {
		return nil
	}
	return i.MaxActiveReq
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetMaxRequestsPerSocket() *int64 {
	if i == nil {
		return nil
	}
	return i.MaxRequestsPerSocket
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetEnableProxyHeader() *bool {
	if i == nil {
		return nil
	}
	return i.EnableProxyHeader
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetCaptureHeaders() *bool {
	if i == nil {
		return nil
	}
	return i.CaptureHeaders
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetActivityLogSampleRate() *float64 {
	if i == nil {
		return nil
	}
	return i.ActivityLogSampleRate
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetRequestTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.RequestTimeout
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetSocketTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.SocketTimeout
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetKeepAliveTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.KeepAliveTimeout
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetEnableHealthCheck() *bool {
	if i == nil {
		return nil
	}
	return i.EnableHealthCheck
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetIPAllowlistRegex() *string {
	if i == nil {
		return nil
	}
	return i.IPAllowlistRegex
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetIPDenylistRegex() *string {
	if i == nil {
		return nil
	}
	return i.IPDenylistRegex
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetBreakerRulesets() []string {
	if i == nil {
		return nil
	}
	return i.BreakerRulesets
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetStaleChannelFlushMs() *float64 {
	if i == nil {
		return nil
	}
	return i.StaleChannelFlushMs
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetMetadata() []ItemsTypeNotificationMetadata {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetAllowedPaths() []string {
	if i == nil {
		return nil
	}
	return i.AllowedPaths
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetAllowedMethods() []string {
	if i == nil {
		return nil
	}
	return i.AllowedMethods
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetAuthTokensExt() []ItemsTypeAuthTokensExt {
	if i == nil {
		return nil
	}
	return i.AuthTokensExt
}

func (i *InputWizWebhookPqEnabledFalseConstraint) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

type InputWizWebhookSendToRoutesFalseWithConnectionsConstraint struct {
	// Select whether to send data to Routes, or directly to Destinations.
	SendToRoutes bool `json:"sendToRoutes"`
	// Direct connections to Destinations, and optionally via a Pipeline or a Pack
	Connections []ItemsTypeConnectionsOptional `json:"connections,omitempty"`
	// Unique ID for this input
	ID       *string             `json:"id,omitempty"`
	Type     InputWizWebhookType `json:"type"`
	Disabled *bool               `json:"disabled,omitempty"`
	// Pipeline to process data from this Source before sending it through the Routes
	Pipeline *string `json:"pipeline,omitempty"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers).
	PqEnabled *bool `json:"pqEnabled,omitempty"`
	// Tags for filtering and grouping in @{product}
	Streamtags []string `json:"streamtags,omitempty"`
	Pq         *PqType  `json:"pq,omitempty"`
	// Address to bind on. Defaults to 0.0.0.0 (all addresses).
	Host string `json:"host"`
	// Port to listen on
	Port float64 `json:"port"`
	// Shared secrets to be provided by any client (Authorization: <token>). If empty, unauthorized access is permitted.
	AuthTokens []string                   `json:"authTokens,omitempty"`
	TLS        *TLSSettingsServerSideType `json:"tls,omitempty"`
	// Maximum number of active requests allowed per Worker Process. Set to 0 for unlimited. Caution: Increasing the limit above the default value, or setting it to unlimited, may degrade performance and reduce throughput.
	MaxActiveReq *float64 `json:"maxActiveReq,omitempty"`
	// Maximum number of requests per socket before @{product} instructs the client to close the connection. Default is 0 (unlimited).
	MaxRequestsPerSocket *int64 `json:"maxRequestsPerSocket,omitempty"`
	// Extract the client IP and port from PROXY protocol v1/v2. When enabled, the X-Forwarded-For header is ignored. Disable to use the X-Forwarded-For header for client IP extraction.
	EnableProxyHeader *bool `json:"enableProxyHeader,omitempty"`
	// Add request headers to events, in the __headers field
	CaptureHeaders *bool `json:"captureHeaders,omitempty"`
	// How often request activity is logged at the `info` level. A value of 1 would log every request, 10 every 10th request, etc.
	ActivityLogSampleRate *float64 `json:"activityLogSampleRate,omitempty"`
	// How long to wait for an incoming request to complete before aborting it. Use 0 to disable.
	RequestTimeout *float64 `json:"requestTimeout,omitempty"`
	// How long @{product} should wait before assuming that an inactive socket has timed out. To wait forever, set to 0.
	SocketTimeout *float64 `json:"socketTimeout,omitempty"`
	// After the last response is sent, @{product} will wait this long for additional data before closing the socket connection. Minimum 1 second, maximum 600 seconds (10 minutes).
	KeepAliveTimeout *float64 `json:"keepAliveTimeout,omitempty"`
	// Expose the /cribl_health endpoint, which returns 200 OK when this Source is healthy
	EnableHealthCheck *bool `json:"enableHealthCheck,omitempty"`
	// Messages from matched IP addresses will be processed, unless also matched by the denylist
	IPAllowlistRegex *string `json:"ipAllowlistRegex,omitempty"`
	// Messages from matched IP addresses will be ignored. This takes precedence over the allowlist.
	IPDenylistRegex *string `json:"ipDenylistRegex,omitempty"`
	// A list of event-breaking rulesets that will be applied, in order, to the input data stream
	BreakerRulesets []string `json:"breakerRulesets,omitempty"`
	// How long (in milliseconds) the Event Breaker will wait for new data to be sent to a specific channel before flushing the data stream out, as is, to the Pipelines
	StaleChannelFlushMs *float64 `json:"staleChannelFlushMs,omitempty"`
	// Fields to add to events from this input
	Metadata []ItemsTypeNotificationMetadata `json:"metadata,omitempty"`
	// List of URI paths accepted by this input. Wildcards are supported (such as /api/v*/hook). Defaults to allow all.
	AllowedPaths []string `json:"allowedPaths,omitempty"`
	// List of HTTP methods accepted by this input. Wildcards are supported (such as P*, GET). Defaults to allow all.
	AllowedMethods []string `json:"allowedMethods,omitempty"`
	// Shared secrets to be provided by any client (Authorization: <token>). If empty, unauthorized access is permitted.
	AuthTokensExt []ItemsTypeAuthTokensExt `json:"authTokensExt,omitempty"`
	Description   *string                  `json:"description,omitempty"`
}

func (i InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"sendToRoutes", "type", "host", "port"}); err != nil {
		return err
	}
	return nil
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetSendToRoutes() bool {
	if i == nil {
		return false
	}
	return i.SendToRoutes
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetConnections() []ItemsTypeConnectionsOptional {
	if i == nil {
		return nil
	}
	return i.Connections
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetType() InputWizWebhookType {
	if i == nil {
		return InputWizWebhookType("")
	}
	return i.Type
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetDisabled() *bool {
	if i == nil {
		return nil
	}
	return i.Disabled
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetPipeline() *string {
	if i == nil {
		return nil
	}
	return i.Pipeline
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetEnvironment() *string {
	if i == nil {
		return nil
	}
	return i.Environment
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetPqEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.PqEnabled
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetStreamtags() []string {
	if i == nil {
		return nil
	}
	return i.Streamtags
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetPq() *PqType {
	if i == nil {
		return nil
	}
	return i.Pq
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetHost() string {
	if i == nil {
		return ""
	}
	return i.Host
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetPort() float64 {
	if i == nil {
		return 0.0
	}
	return i.Port
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetAuthTokens() []string {
	if i == nil {
		return nil
	}
	return i.AuthTokens
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetTLS() *TLSSettingsServerSideType {
	if i == nil {
		return nil
	}
	return i.TLS
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetMaxActiveReq() *float64 {
	if i == nil {
		return nil
	}
	return i.MaxActiveReq
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetMaxRequestsPerSocket() *int64 {
	if i == nil {
		return nil
	}
	return i.MaxRequestsPerSocket
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetEnableProxyHeader() *bool {
	if i == nil {
		return nil
	}
	return i.EnableProxyHeader
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetCaptureHeaders() *bool {
	if i == nil {
		return nil
	}
	return i.CaptureHeaders
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetActivityLogSampleRate() *float64 {
	if i == nil {
		return nil
	}
	return i.ActivityLogSampleRate
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetRequestTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.RequestTimeout
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetSocketTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.SocketTimeout
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetKeepAliveTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.KeepAliveTimeout
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetEnableHealthCheck() *bool {
	if i == nil {
		return nil
	}
	return i.EnableHealthCheck
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetIPAllowlistRegex() *string {
	if i == nil {
		return nil
	}
	return i.IPAllowlistRegex
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetIPDenylistRegex() *string {
	if i == nil {
		return nil
	}
	return i.IPDenylistRegex
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetBreakerRulesets() []string {
	if i == nil {
		return nil
	}
	return i.BreakerRulesets
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetStaleChannelFlushMs() *float64 {
	if i == nil {
		return nil
	}
	return i.StaleChannelFlushMs
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetMetadata() []ItemsTypeNotificationMetadata {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetAllowedPaths() []string {
	if i == nil {
		return nil
	}
	return i.AllowedPaths
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetAllowedMethods() []string {
	if i == nil {
		return nil
	}
	return i.AllowedMethods
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetAuthTokensExt() []ItemsTypeAuthTokensExt {
	if i == nil {
		return nil
	}
	return i.AuthTokensExt
}

func (i *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

type InputWizWebhookType string

const (
	InputWizWebhookTypeWizWebhook InputWizWebhookType = "wiz_webhook"
)

func (e InputWizWebhookType) ToPointer() *InputWizWebhookType {
	return &e
}
func (e *InputWizWebhookType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "wiz_webhook":
		*e = InputWizWebhookType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputWizWebhookType: %v", v)
	}
}

type InputWizWebhookSendToRoutesTrueConstraint struct {
	// Select whether to send data to Routes, or directly to Destinations.
	SendToRoutes bool `json:"sendToRoutes"`
	// Unique ID for this input
	ID       *string             `json:"id,omitempty"`
	Type     InputWizWebhookType `json:"type"`
	Disabled *bool               `json:"disabled,omitempty"`
	// Pipeline to process data from this Source before sending it through the Routes
	Pipeline *string `json:"pipeline,omitempty"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers).
	PqEnabled *bool `json:"pqEnabled,omitempty"`
	// Tags for filtering and grouping in @{product}
	Streamtags []string `json:"streamtags,omitempty"`
	// Direct connections to Destinations, and optionally via a Pipeline or a Pack
	Connections []ItemsTypeConnectionsOptional `json:"connections,omitempty"`
	Pq          *PqType                        `json:"pq,omitempty"`
	// Address to bind on. Defaults to 0.0.0.0 (all addresses).
	Host string `json:"host"`
	// Port to listen on
	Port float64 `json:"port"`
	// Shared secrets to be provided by any client (Authorization: <token>). If empty, unauthorized access is permitted.
	AuthTokens []string                   `json:"authTokens,omitempty"`
	TLS        *TLSSettingsServerSideType `json:"tls,omitempty"`
	// Maximum number of active requests allowed per Worker Process. Set to 0 for unlimited. Caution: Increasing the limit above the default value, or setting it to unlimited, may degrade performance and reduce throughput.
	MaxActiveReq *float64 `json:"maxActiveReq,omitempty"`
	// Maximum number of requests per socket before @{product} instructs the client to close the connection. Default is 0 (unlimited).
	MaxRequestsPerSocket *int64 `json:"maxRequestsPerSocket,omitempty"`
	// Extract the client IP and port from PROXY protocol v1/v2. When enabled, the X-Forwarded-For header is ignored. Disable to use the X-Forwarded-For header for client IP extraction.
	EnableProxyHeader *bool `json:"enableProxyHeader,omitempty"`
	// Add request headers to events, in the __headers field
	CaptureHeaders *bool `json:"captureHeaders,omitempty"`
	// How often request activity is logged at the `info` level. A value of 1 would log every request, 10 every 10th request, etc.
	ActivityLogSampleRate *float64 `json:"activityLogSampleRate,omitempty"`
	// How long to wait for an incoming request to complete before aborting it. Use 0 to disable.
	RequestTimeout *float64 `json:"requestTimeout,omitempty"`
	// How long @{product} should wait before assuming that an inactive socket has timed out. To wait forever, set to 0.
	SocketTimeout *float64 `json:"socketTimeout,omitempty"`
	// After the last response is sent, @{product} will wait this long for additional data before closing the socket connection. Minimum 1 second, maximum 600 seconds (10 minutes).
	KeepAliveTimeout *float64 `json:"keepAliveTimeout,omitempty"`
	// Expose the /cribl_health endpoint, which returns 200 OK when this Source is healthy
	EnableHealthCheck *bool `json:"enableHealthCheck,omitempty"`
	// Messages from matched IP addresses will be processed, unless also matched by the denylist
	IPAllowlistRegex *string `json:"ipAllowlistRegex,omitempty"`
	// Messages from matched IP addresses will be ignored. This takes precedence over the allowlist.
	IPDenylistRegex *string `json:"ipDenylistRegex,omitempty"`
	// A list of event-breaking rulesets that will be applied, in order, to the input data stream
	BreakerRulesets []string `json:"breakerRulesets,omitempty"`
	// How long (in milliseconds) the Event Breaker will wait for new data to be sent to a specific channel before flushing the data stream out, as is, to the Pipelines
	StaleChannelFlushMs *float64 `json:"staleChannelFlushMs,omitempty"`
	// Fields to add to events from this input
	Metadata []ItemsTypeNotificationMetadata `json:"metadata,omitempty"`
	// List of URI paths accepted by this input. Wildcards are supported (such as /api/v*/hook). Defaults to allow all.
	AllowedPaths []string `json:"allowedPaths,omitempty"`
	// List of HTTP methods accepted by this input. Wildcards are supported (such as P*, GET). Defaults to allow all.
	AllowedMethods []string `json:"allowedMethods,omitempty"`
	// Shared secrets to be provided by any client (Authorization: <token>). If empty, unauthorized access is permitted.
	AuthTokensExt []ItemsTypeAuthTokensExt `json:"authTokensExt,omitempty"`
	Description   *string                  `json:"description,omitempty"`
}

func (i InputWizWebhookSendToRoutesTrueConstraint) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"sendToRoutes", "type", "host", "port"}); err != nil {
		return err
	}
	return nil
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetSendToRoutes() bool {
	if i == nil {
		return false
	}
	return i.SendToRoutes
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetType() InputWizWebhookType {
	if i == nil {
		return InputWizWebhookType("")
	}
	return i.Type
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetDisabled() *bool {
	if i == nil {
		return nil
	}
	return i.Disabled
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetPipeline() *string {
	if i == nil {
		return nil
	}
	return i.Pipeline
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetEnvironment() *string {
	if i == nil {
		return nil
	}
	return i.Environment
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetPqEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.PqEnabled
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetStreamtags() []string {
	if i == nil {
		return nil
	}
	return i.Streamtags
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetConnections() []ItemsTypeConnectionsOptional {
	if i == nil {
		return nil
	}
	return i.Connections
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetPq() *PqType {
	if i == nil {
		return nil
	}
	return i.Pq
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetHost() string {
	if i == nil {
		return ""
	}
	return i.Host
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetPort() float64 {
	if i == nil {
		return 0.0
	}
	return i.Port
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetAuthTokens() []string {
	if i == nil {
		return nil
	}
	return i.AuthTokens
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetTLS() *TLSSettingsServerSideType {
	if i == nil {
		return nil
	}
	return i.TLS
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetMaxActiveReq() *float64 {
	if i == nil {
		return nil
	}
	return i.MaxActiveReq
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetMaxRequestsPerSocket() *int64 {
	if i == nil {
		return nil
	}
	return i.MaxRequestsPerSocket
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetEnableProxyHeader() *bool {
	if i == nil {
		return nil
	}
	return i.EnableProxyHeader
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetCaptureHeaders() *bool {
	if i == nil {
		return nil
	}
	return i.CaptureHeaders
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetActivityLogSampleRate() *float64 {
	if i == nil {
		return nil
	}
	return i.ActivityLogSampleRate
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetRequestTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.RequestTimeout
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetSocketTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.SocketTimeout
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetKeepAliveTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.KeepAliveTimeout
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetEnableHealthCheck() *bool {
	if i == nil {
		return nil
	}
	return i.EnableHealthCheck
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetIPAllowlistRegex() *string {
	if i == nil {
		return nil
	}
	return i.IPAllowlistRegex
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetIPDenylistRegex() *string {
	if i == nil {
		return nil
	}
	return i.IPDenylistRegex
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetBreakerRulesets() []string {
	if i == nil {
		return nil
	}
	return i.BreakerRulesets
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetStaleChannelFlushMs() *float64 {
	if i == nil {
		return nil
	}
	return i.StaleChannelFlushMs
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetMetadata() []ItemsTypeNotificationMetadata {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetAllowedPaths() []string {
	if i == nil {
		return nil
	}
	return i.AllowedPaths
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetAllowedMethods() []string {
	if i == nil {
		return nil
	}
	return i.AllowedMethods
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetAuthTokensExt() []ItemsTypeAuthTokensExt {
	if i == nil {
		return nil
	}
	return i.AuthTokensExt
}

func (i *InputWizWebhookSendToRoutesTrueConstraint) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

type InputWizWebhookUnionType string

const (
	InputWizWebhookUnionTypeInputWizWebhookSendToRoutesTrueConstraint                 InputWizWebhookUnionType = "InputWizWebhook_SendToRoutesTrueConstraint"
	InputWizWebhookUnionTypeInputWizWebhookSendToRoutesFalseWithConnectionsConstraint InputWizWebhookUnionType = "InputWizWebhook_SendToRoutesFalseWithConnectionsConstraint"
	InputWizWebhookUnionTypeInputWizWebhookPqEnabledFalseConstraint                   InputWizWebhookUnionType = "InputWizWebhook_PqEnabledFalseConstraint"
	InputWizWebhookUnionTypeInputWizWebhookPqEnabledTrueWithPqConstraint              InputWizWebhookUnionType = "InputWizWebhook_PqEnabledTrueWithPqConstraint"
)

type InputWizWebhook struct {
	InputWizWebhookSendToRoutesTrueConstraint                 *InputWizWebhookSendToRoutesTrueConstraint                 `queryParam:"inline" union:"member"`
	InputWizWebhookSendToRoutesFalseWithConnectionsConstraint *InputWizWebhookSendToRoutesFalseWithConnectionsConstraint `queryParam:"inline" union:"member"`
	InputWizWebhookPqEnabledFalseConstraint                   *InputWizWebhookPqEnabledFalseConstraint                   `queryParam:"inline" union:"member"`
	InputWizWebhookPqEnabledTrueWithPqConstraint              *InputWizWebhookPqEnabledTrueWithPqConstraint              `queryParam:"inline" union:"member"`

	Type InputWizWebhookUnionType
}

func CreateInputWizWebhookInputWizWebhookSendToRoutesTrueConstraint(inputWizWebhookSendToRoutesTrueConstraint InputWizWebhookSendToRoutesTrueConstraint) InputWizWebhook {
	typ := InputWizWebhookUnionTypeInputWizWebhookSendToRoutesTrueConstraint

	return InputWizWebhook{
		InputWizWebhookSendToRoutesTrueConstraint: &inputWizWebhookSendToRoutesTrueConstraint,
		Type: typ,
	}
}

func CreateInputWizWebhookInputWizWebhookSendToRoutesFalseWithConnectionsConstraint(inputWizWebhookSendToRoutesFalseWithConnectionsConstraint InputWizWebhookSendToRoutesFalseWithConnectionsConstraint) InputWizWebhook {
	typ := InputWizWebhookUnionTypeInputWizWebhookSendToRoutesFalseWithConnectionsConstraint

	return InputWizWebhook{
		InputWizWebhookSendToRoutesFalseWithConnectionsConstraint: &inputWizWebhookSendToRoutesFalseWithConnectionsConstraint,
		Type: typ,
	}
}

func CreateInputWizWebhookInputWizWebhookPqEnabledFalseConstraint(inputWizWebhookPqEnabledFalseConstraint InputWizWebhookPqEnabledFalseConstraint) InputWizWebhook {
	typ := InputWizWebhookUnionTypeInputWizWebhookPqEnabledFalseConstraint

	return InputWizWebhook{
		InputWizWebhookPqEnabledFalseConstraint: &inputWizWebhookPqEnabledFalseConstraint,
		Type:                                    typ,
	}
}

func CreateInputWizWebhookInputWizWebhookPqEnabledTrueWithPqConstraint(inputWizWebhookPqEnabledTrueWithPqConstraint InputWizWebhookPqEnabledTrueWithPqConstraint) InputWizWebhook {
	typ := InputWizWebhookUnionTypeInputWizWebhookPqEnabledTrueWithPqConstraint

	return InputWizWebhook{
		InputWizWebhookPqEnabledTrueWithPqConstraint: &inputWizWebhookPqEnabledTrueWithPqConstraint,
		Type: typ,
	}
}

func (u *InputWizWebhook) UnmarshalJSON(data []byte) error {

	var inputWizWebhookSendToRoutesTrueConstraint InputWizWebhookSendToRoutesTrueConstraint = InputWizWebhookSendToRoutesTrueConstraint{}
	if err := utils.UnmarshalJSON(data, &inputWizWebhookSendToRoutesTrueConstraint, "", true, nil); err == nil {
		u.InputWizWebhookSendToRoutesTrueConstraint = &inputWizWebhookSendToRoutesTrueConstraint
		u.Type = InputWizWebhookUnionTypeInputWizWebhookSendToRoutesTrueConstraint
		return nil
	}

	var inputWizWebhookSendToRoutesFalseWithConnectionsConstraint InputWizWebhookSendToRoutesFalseWithConnectionsConstraint = InputWizWebhookSendToRoutesFalseWithConnectionsConstraint{}
	if err := utils.UnmarshalJSON(data, &inputWizWebhookSendToRoutesFalseWithConnectionsConstraint, "", true, nil); err == nil {
		u.InputWizWebhookSendToRoutesFalseWithConnectionsConstraint = &inputWizWebhookSendToRoutesFalseWithConnectionsConstraint
		u.Type = InputWizWebhookUnionTypeInputWizWebhookSendToRoutesFalseWithConnectionsConstraint
		return nil
	}

	var inputWizWebhookPqEnabledFalseConstraint InputWizWebhookPqEnabledFalseConstraint = InputWizWebhookPqEnabledFalseConstraint{}
	if err := utils.UnmarshalJSON(data, &inputWizWebhookPqEnabledFalseConstraint, "", true, nil); err == nil {
		u.InputWizWebhookPqEnabledFalseConstraint = &inputWizWebhookPqEnabledFalseConstraint
		u.Type = InputWizWebhookUnionTypeInputWizWebhookPqEnabledFalseConstraint
		return nil
	}

	var inputWizWebhookPqEnabledTrueWithPqConstraint InputWizWebhookPqEnabledTrueWithPqConstraint = InputWizWebhookPqEnabledTrueWithPqConstraint{}
	if err := utils.UnmarshalJSON(data, &inputWizWebhookPqEnabledTrueWithPqConstraint, "", true, nil); err == nil {
		u.InputWizWebhookPqEnabledTrueWithPqConstraint = &inputWizWebhookPqEnabledTrueWithPqConstraint
		u.Type = InputWizWebhookUnionTypeInputWizWebhookPqEnabledTrueWithPqConstraint
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for InputWizWebhook", string(data))
}

func (u InputWizWebhook) MarshalJSON() ([]byte, error) {
	if u.InputWizWebhookSendToRoutesTrueConstraint != nil {
		return utils.MarshalJSON(u.InputWizWebhookSendToRoutesTrueConstraint, "", true)
	}

	if u.InputWizWebhookSendToRoutesFalseWithConnectionsConstraint != nil {
		return utils.MarshalJSON(u.InputWizWebhookSendToRoutesFalseWithConnectionsConstraint, "", true)
	}

	if u.InputWizWebhookPqEnabledFalseConstraint != nil {
		return utils.MarshalJSON(u.InputWizWebhookPqEnabledFalseConstraint, "", true)
	}

	if u.InputWizWebhookPqEnabledTrueWithPqConstraint != nil {
		return utils.MarshalJSON(u.InputWizWebhookPqEnabledTrueWithPqConstraint, "", true)
	}

	return nil, errors.New("could not marshal union type InputWizWebhook: all fields are null")
}
