// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type ItemsTypeRoutesInputRoutes struct {
	// Array of clone configurations, each with a key-value pair to set or overwrite in cloned events. Original events continue to the next Route.
	Clones []map[string]string `json:"clones,omitzero"`
	// Context for the Route: <code>group</code> (Worker Group or Edge Fleet) or <code>pack</code>.
	Context *string `json:"context,omitzero"`
	// Brief description of the Route.
	Description *string `json:"description,omitzero"`
	// If <code>true</code>, disable the Route. Otherwise, <code>false</code>.
	Disabled *bool `json:"disabled,omitzero"`
	// If <code>true</code>, use the <code>outputExpression</code> for dynamic Destination selection. Otherwise, <code>false</code>.
	EnableOutputExpression *bool `json:"enableOutputExpression,omitzero"`
	// JavaScript expression to select events for routing.
	Filter *string `json:"filter,omitzero"`
	// Unique identifier for the Route Group that the Route is associated with.
	GroupID *string `json:"groupId,omitzero"`
	// Name of the Route.
	Name string `json:"name"`
	// Destination that the Route sends matching events to after the Pipeline processes the events.
	Output *string `json:"output,omitzero"`
	// JavaScript expression to evaluate for dynamic Destination selection. Evaluation occurs when the Route is constructed, not for each event.
	OutputExpression *string `json:"outputExpression,omitzero"`
	// Pipeline that the Route sends matching events to.
	Pipeline      string         `json:"pipeline"`
	TargetContext *TargetContext `json:"targetContext,omitzero"`
	// If <code>true</code> (default), the Route processes matched events and sends them to the specified Pipeline. Matched events do not continue to the next Route, but non-matched events do continue to the next Route. If <code>false</code>, the Route processes matched events and sends them to the specified Pipeline, and all events (matched and non-matched) continue to the next Route. Must be <code>false</code> to clone events.
	Final *bool `json:"final,omitzero"`
	// Unique identifier for the Route. If omitted, the server generates a deterministic identifier.
	ID *string `json:"id,omitzero"`
}

func (i ItemsTypeRoutesInputRoutes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ItemsTypeRoutesInputRoutes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ItemsTypeRoutesInputRoutes) GetClones() []map[string]string {
	if i == nil {
		return nil
	}
	return i.Clones
}

func (i *ItemsTypeRoutesInputRoutes) GetContext() *string {
	if i == nil {
		return nil
	}
	return i.Context
}

func (i *ItemsTypeRoutesInputRoutes) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *ItemsTypeRoutesInputRoutes) GetDisabled() *bool {
	if i == nil {
		return nil
	}
	return i.Disabled
}

func (i *ItemsTypeRoutesInputRoutes) GetEnableOutputExpression() *bool {
	if i == nil {
		return nil
	}
	return i.EnableOutputExpression
}

func (i *ItemsTypeRoutesInputRoutes) GetFilter() *string {
	if i == nil {
		return nil
	}
	return i.Filter
}

func (i *ItemsTypeRoutesInputRoutes) GetGroupID() *string {
	if i == nil {
		return nil
	}
	return i.GroupID
}

func (i *ItemsTypeRoutesInputRoutes) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *ItemsTypeRoutesInputRoutes) GetOutput() *string {
	if i == nil {
		return nil
	}
	return i.Output
}

func (i *ItemsTypeRoutesInputRoutes) GetOutputExpression() *string {
	if i == nil {
		return nil
	}
	return i.OutputExpression
}

func (i *ItemsTypeRoutesInputRoutes) GetPipeline() string {
	if i == nil {
		return ""
	}
	return i.Pipeline
}

func (i *ItemsTypeRoutesInputRoutes) GetTargetContext() *TargetContext {
	if i == nil {
		return nil
	}
	return i.TargetContext
}

func (i *ItemsTypeRoutesInputRoutes) GetFinal() *bool {
	if i == nil {
		return nil
	}
	return i.Final
}

func (i *ItemsTypeRoutesInputRoutes) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}
