// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MasterWorkerEntryType string

const (
	MasterWorkerEntryTypeInfo MasterWorkerEntryType = "info"
	MasterWorkerEntryTypeReq  MasterWorkerEntryType = "req"
	MasterWorkerEntryTypeResp MasterWorkerEntryType = "resp"
)

func (e MasterWorkerEntryType) ToPointer() *MasterWorkerEntryType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MasterWorkerEntryType) IsExact() bool {
	if e != nil {
		switch *e {
		case "info", "req", "resp":
			return true
		}
	}
	return false
}

type MasterWorkerEntryWorkers struct {
	Count float64 `json:"count"`
}

func (m *MasterWorkerEntryWorkers) GetCount() float64 {
	if m == nil {
		return 0.0
	}
	return m.Count
}

type MasterWorkerEntry struct {
	ConnectionProtocol *ConnectionProtocol       `json:"connectionProtocol,omitempty"`
	Deployable         *bool                     `json:"deployable,omitempty"`
	Disconnected       *bool                     `json:"disconnected,omitempty"`
	FirstMsgTime       float64                   `json:"firstMsgTime"`
	Group              string                    `json:"group"`
	ID                 string                    `json:"id"`
	Info               NodeProvidedInfo          `json:"info"`
	LastMetrics        map[string]any            `json:"lastMetrics,omitempty"`
	LastMsgTime        float64                   `json:"lastMsgTime"`
	Metadata           *HeartbeatMetadata        `json:"metadata,omitempty"`
	NodeUpgradeStatus  *NodeUpgradeStatus        `json:"nodeUpgradeStatus,omitempty"`
	Status             *string                   `json:"status,omitempty"`
	Type               *MasterWorkerEntryType    `json:"type,omitempty"`
	WorkerProcesses    float64                   `json:"workerProcesses"`
	Workers            *MasterWorkerEntryWorkers `json:"workers,omitempty"`
}

func (m *MasterWorkerEntry) GetConnectionProtocol() *ConnectionProtocol {
	if m == nil {
		return nil
	}
	return m.ConnectionProtocol
}

func (m *MasterWorkerEntry) GetDeployable() *bool {
	if m == nil {
		return nil
	}
	return m.Deployable
}

func (m *MasterWorkerEntry) GetDisconnected() *bool {
	if m == nil {
		return nil
	}
	return m.Disconnected
}

func (m *MasterWorkerEntry) GetFirstMsgTime() float64 {
	if m == nil {
		return 0.0
	}
	return m.FirstMsgTime
}

func (m *MasterWorkerEntry) GetGroup() string {
	if m == nil {
		return ""
	}
	return m.Group
}

func (m *MasterWorkerEntry) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MasterWorkerEntry) GetInfo() NodeProvidedInfo {
	if m == nil {
		return NodeProvidedInfo{}
	}
	return m.Info
}

func (m *MasterWorkerEntry) GetLastMetrics() map[string]any {
	if m == nil {
		return nil
	}
	return m.LastMetrics
}

func (m *MasterWorkerEntry) GetLastMsgTime() float64 {
	if m == nil {
		return 0.0
	}
	return m.LastMsgTime
}

func (m *MasterWorkerEntry) GetMetadata() *HeartbeatMetadata {
	if m == nil {
		return nil
	}
	return m.Metadata
}

func (m *MasterWorkerEntry) GetNodeUpgradeStatus() *NodeUpgradeStatus {
	if m == nil {
		return nil
	}
	return m.NodeUpgradeStatus
}

func (m *MasterWorkerEntry) GetStatus() *string {
	if m == nil {
		return nil
	}
	return m.Status
}

func (m *MasterWorkerEntry) GetType() *MasterWorkerEntryType {
	if m == nil {
		return nil
	}
	return m.Type
}

func (m *MasterWorkerEntry) GetWorkerProcesses() float64 {
	if m == nil {
		return 0.0
	}
	return m.WorkerProcesses
}

func (m *MasterWorkerEntry) GetWorkers() *MasterWorkerEntryWorkers {
	if m == nil {
		return nil
	}
	return m.Workers
}
