// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MetadataItem struct {
	// Field name. Must be a valid identifier (letter, underscore, or $ followed by alphanumeric, or quoted). Surround with quotes or backticks if the name contains special characters.
	Name string `json:"name"`
	// JavaScript expression to compute the field value, enclosed in quotes or backticks. Can evaluate to a constant.
	Value string `json:"value"`
}

func (m *MetadataItem) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MetadataItem) GetValue() string {
	if m == nil {
		return ""
	}
	return m.Value
}
