// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type OrphanFileRecoveryType struct {
	// Periodically scan the staging directory for files not tracked by any Worker manifest to recover them
	Disabled *bool `json:"disabled,omitzero"`
	// Minimum interval between reconciliation runs
	PeriodMin *float64 `json:"periodMin,omitzero"`
}

func (o OrphanFileRecoveryType) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrphanFileRecoveryType) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrphanFileRecoveryType) GetDisabled() *bool {
	if o == nil {
		return nil
	}
	return o.Disabled
}

func (o *OrphanFileRecoveryType) GetPeriodMin() *float64 {
	if o == nil {
		return nil
	}
	return o.PeriodMin
}
