// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

// PipelineFunctionPublishMetricsID - Function ID
type PipelineFunctionPublishMetricsID string

const (
	PipelineFunctionPublishMetricsIDPublishMetrics PipelineFunctionPublishMetricsID = "publish_metrics"
)

func (e PipelineFunctionPublishMetricsID) ToPointer() *PipelineFunctionPublishMetricsID {
	return &e
}
func (e *PipelineFunctionPublishMetricsID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "publish_metrics":
		*e = PipelineFunctionPublishMetricsID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PipelineFunctionPublishMetricsID: %v", v)
	}
}

type PipelineFunctionPublishMetrics struct {
	// Filter that selects data to be fed through this Function
	Filter *string `json:"filter,omitempty"`
	// Function ID
	ID PipelineFunctionPublishMetricsID `json:"id"`
	// Simple description of this step
	Description *string `json:"description,omitempty"`
	// If true, data will not be pushed through this function
	Disabled *bool `json:"disabled,omitempty"`
	// If enabled, stops the results of this Function from being passed to the downstream Functions
	Final *bool                            `json:"final,omitempty"`
	Conf  FunctionConfSchemaPublishMetrics `json:"conf"`
	// Group ID
	GroupID *string `json:"groupId,omitempty"`
}

func (p PipelineFunctionPublishMetrics) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PipelineFunctionPublishMetrics) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PipelineFunctionPublishMetrics) GetFilter() *string {
	if p == nil {
		return nil
	}
	return p.Filter
}

func (p *PipelineFunctionPublishMetrics) GetID() PipelineFunctionPublishMetricsID {
	if p == nil {
		return PipelineFunctionPublishMetricsID("")
	}
	return p.ID
}

func (p *PipelineFunctionPublishMetrics) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PipelineFunctionPublishMetrics) GetDisabled() *bool {
	if p == nil {
		return nil
	}
	return p.Disabled
}

func (p *PipelineFunctionPublishMetrics) GetFinal() *bool {
	if p == nil {
		return nil
	}
	return p.Final
}

func (p *PipelineFunctionPublishMetrics) GetConf() FunctionConfSchemaPublishMetrics {
	if p == nil {
		return FunctionConfSchemaPublishMetrics{}
	}
	return p.Conf
}

func (p *PipelineFunctionPublishMetrics) GetGroupID() *string {
	if p == nil {
		return nil
	}
	return p.GroupID
}
