// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

// PipelineFunctionSendID - Function ID
type PipelineFunctionSendID string

const (
	PipelineFunctionSendIDSend PipelineFunctionSendID = "send"
)

func (e PipelineFunctionSendID) ToPointer() *PipelineFunctionSendID {
	return &e
}
func (e *PipelineFunctionSendID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "send":
		*e = PipelineFunctionSendID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PipelineFunctionSendID: %v", v)
	}
}

type PipelineFunctionSend struct {
	// Filter that selects data to be fed through this Function
	Filter *string `json:"filter,omitempty"`
	// Function ID
	ID PipelineFunctionSendID `json:"id"`
	// Simple description of this step
	Description *string `json:"description,omitempty"`
	// If true, data will not be pushed through this function
	Disabled *bool `json:"disabled,omitempty"`
	// If enabled, stops the results of this Function from being passed to the downstream Functions
	Final *bool                  `json:"final,omitempty"`
	Conf  FunctionConfSchemaSend `json:"conf"`
	// Group ID
	GroupID *string `json:"groupId,omitempty"`
}

func (p PipelineFunctionSend) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PipelineFunctionSend) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"id", "conf"}); err != nil {
		return err
	}
	return nil
}

func (p *PipelineFunctionSend) GetFilter() *string {
	if p == nil {
		return nil
	}
	return p.Filter
}

func (p *PipelineFunctionSend) GetID() PipelineFunctionSendID {
	if p == nil {
		return PipelineFunctionSendID("")
	}
	return p.ID
}

func (p *PipelineFunctionSend) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PipelineFunctionSend) GetDisabled() *bool {
	if p == nil {
		return nil
	}
	return p.Disabled
}

func (p *PipelineFunctionSend) GetFinal() *bool {
	if p == nil {
		return nil
	}
	return p.Final
}

func (p *PipelineFunctionSend) GetConf() FunctionConfSchemaSend {
	if p == nil {
		return FunctionConfSchemaSend{}
	}
	return p.Conf
}

func (p *PipelineFunctionSend) GetGroupID() *string {
	if p == nil {
		return nil
	}
	return p.GroupID
}
