// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

// PipelineFunctionJoinID - Function ID
type PipelineFunctionJoinID string

const (
	PipelineFunctionJoinIDJoin PipelineFunctionJoinID = "join"
)

func (e PipelineFunctionJoinID) ToPointer() *PipelineFunctionJoinID {
	return &e
}
func (e *PipelineFunctionJoinID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "join":
		*e = PipelineFunctionJoinID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PipelineFunctionJoinID: %v", v)
	}
}

type FieldCondition struct {
	// The field name to join on, on the left side.
	LeftFieldName string `json:"leftFieldName"`
	// The field name on the right side of the data, i.e. the stage results, that we are joining with
	RightFieldName string `json:"rightFieldName"`
}

func (f FieldCondition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FieldCondition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FieldCondition) GetLeftFieldName() string {
	if f == nil {
		return ""
	}
	return f.LeftFieldName
}

func (f *FieldCondition) GetRightFieldName() string {
	if f == nil {
		return ""
	}
	return f.RightFieldName
}

type JoinConfiguration struct {
	// Join kind, e.g. inner
	Kind *string `json:"kind,omitzero"`
	// Hints passed to the join function
	Hints map[string]string `json:"hints,omitzero"`
	// Fields to use when joining
	FieldConditions []FieldCondition `json:"fieldConditions"`
	// The id for this search job.
	SearchJobID *string `json:"searchJobId,omitzero"`
	// The stage we are joining with.
	StageID *string `json:"stageId,omitzero"`
}

func (j JoinConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JoinConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *JoinConfiguration) GetKind() *string {
	if j == nil {
		return nil
	}
	return j.Kind
}

func (j *JoinConfiguration) GetHints() map[string]string {
	if j == nil {
		return nil
	}
	return j.Hints
}

func (j *JoinConfiguration) GetFieldConditions() []FieldCondition {
	if j == nil {
		return []FieldCondition{}
	}
	return j.FieldConditions
}

func (j *JoinConfiguration) GetSearchJobID() *string {
	if j == nil {
		return nil
	}
	return j.SearchJobID
}

func (j *JoinConfiguration) GetStageID() *string {
	if j == nil {
		return nil
	}
	return j.StageID
}

type PipelineFunctionJoin struct {
	// Filter that selects data to be fed through this Function
	Filter *string `json:"filter,omitzero"`
	// Function ID
	ID PipelineFunctionJoinID `json:"id"`
	// Simple description of this step
	Description *string `json:"description,omitzero"`
	// If true, data will not be pushed through this function
	Disabled *bool `json:"disabled,omitzero"`
	// If enabled, stops the results of this Function from being passed to the downstream Functions
	Final *bool             `json:"final,omitzero"`
	Conf  JoinConfiguration `json:"conf"`
	// Group ID
	GroupID *string `json:"groupId,omitzero"`
}

func (p PipelineFunctionJoin) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PipelineFunctionJoin) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PipelineFunctionJoin) GetFilter() *string {
	if p == nil {
		return nil
	}
	return p.Filter
}

func (p *PipelineFunctionJoin) GetID() PipelineFunctionJoinID {
	if p == nil {
		return PipelineFunctionJoinID("")
	}
	return p.ID
}

func (p *PipelineFunctionJoin) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PipelineFunctionJoin) GetDisabled() *bool {
	if p == nil {
		return nil
	}
	return p.Disabled
}

func (p *PipelineFunctionJoin) GetFinal() *bool {
	if p == nil {
		return nil
	}
	return p.Final
}

func (p *PipelineFunctionJoin) GetConf() JoinConfiguration {
	if p == nil {
		return JoinConfiguration{}
	}
	return p.Conf
}

func (p *PipelineFunctionJoin) GetGroupID() *string {
	if p == nil {
		return nil
	}
	return p.GroupID
}
