// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

// PipelineFunctionCodeID - Function ID
type PipelineFunctionCodeID string

const (
	PipelineFunctionCodeIDCode PipelineFunctionCodeID = "code"
)

func (e PipelineFunctionCodeID) ToPointer() *PipelineFunctionCodeID {
	return &e
}
func (e *PipelineFunctionCodeID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "code":
		*e = PipelineFunctionCodeID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PipelineFunctionCodeID: %v", v)
	}
}

type PipelineFunctionCode struct {
	// Filter that selects data to be fed through this Function
	Filter *string `json:"filter,omitzero"`
	// Function ID
	ID PipelineFunctionCodeID `json:"id"`
	// Simple description of this step
	Description *string `json:"description,omitzero"`
	// If true, data will not be pushed through this function
	Disabled *bool `json:"disabled,omitzero"`
	// If enabled, stops the results of this Function from being passed to the downstream Functions
	Final *bool                  `json:"final,omitzero"`
	Conf  FunctionConfSchemaCode `json:"conf"`
	// Group ID
	GroupID *string `json:"groupId,omitzero"`
}

func (p PipelineFunctionCode) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PipelineFunctionCode) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PipelineFunctionCode) GetFilter() *string {
	if p == nil {
		return nil
	}
	return p.Filter
}

func (p *PipelineFunctionCode) GetID() PipelineFunctionCodeID {
	if p == nil {
		return PipelineFunctionCodeID("")
	}
	return p.ID
}

func (p *PipelineFunctionCode) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PipelineFunctionCode) GetDisabled() *bool {
	if p == nil {
		return nil
	}
	return p.Disabled
}

func (p *PipelineFunctionCode) GetFinal() *bool {
	if p == nil {
		return nil
	}
	return p.Final
}

func (p *PipelineFunctionCode) GetConf() FunctionConfSchemaCode {
	if p == nil {
		return FunctionConfSchemaCode{}
	}
	return p.Conf
}

func (p *PipelineFunctionCode) GetGroupID() *string {
	if p == nil {
		return nil
	}
	return p.GroupID
}
