// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7c7668fabeb3

package components

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

// PipelineFunctionExternaldataID - Function ID
type PipelineFunctionExternaldataID string

const (
	PipelineFunctionExternaldataIDExternaldata PipelineFunctionExternaldataID = "externaldata"
)

func (e PipelineFunctionExternaldataID) ToPointer() *PipelineFunctionExternaldataID {
	return &e
}
func (e *PipelineFunctionExternaldataID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "externaldata":
		*e = PipelineFunctionExternaldataID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PipelineFunctionExternaldataID: %v", v)
	}
}

type PipelineFunctionExternaldata struct {
	// Filter that selects data to be fed through this Function
	Filter *string `json:"filter,omitempty"`
	// Function ID
	ID PipelineFunctionExternaldataID `json:"id"`
	// Simple description of this step
	Description *string `json:"description,omitempty"`
	// If true, data will not be pushed through this function
	Disabled *bool `json:"disabled,omitempty"`
	// If enabled, stops the results of this Function from being passed to the downstream Functions
	Final *bool                          `json:"final,omitempty"`
	Conf  FunctionConfSchemaExternaldata `json:"conf"`
	// Group ID
	GroupID *string `json:"groupId,omitempty"`
}

func (p PipelineFunctionExternaldata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PipelineFunctionExternaldata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PipelineFunctionExternaldata) GetFilter() *string {
	if p == nil {
		return nil
	}
	return p.Filter
}

func (p *PipelineFunctionExternaldata) GetID() PipelineFunctionExternaldataID {
	if p == nil {
		return PipelineFunctionExternaldataID("")
	}
	return p.ID
}

func (p *PipelineFunctionExternaldata) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PipelineFunctionExternaldata) GetDisabled() *bool {
	if p == nil {
		return nil
	}
	return p.Disabled
}

func (p *PipelineFunctionExternaldata) GetFinal() *bool {
	if p == nil {
		return nil
	}
	return p.Final
}

func (p *PipelineFunctionExternaldata) GetConf() FunctionConfSchemaExternaldata {
	if p == nil {
		return FunctionConfSchemaExternaldata{}
	}
	return p.Conf
}

func (p *PipelineFunctionExternaldata) GetGroupID() *string {
	if p == nil {
		return nil
	}
	return p.GroupID
}
