// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

// PipelineFunctionRegexExtractID - Function ID
type PipelineFunctionRegexExtractID string

const (
	PipelineFunctionRegexExtractIDRegexExtract PipelineFunctionRegexExtractID = "regex_extract"
)

func (e PipelineFunctionRegexExtractID) ToPointer() *PipelineFunctionRegexExtractID {
	return &e
}
func (e *PipelineFunctionRegexExtractID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "regex_extract":
		*e = PipelineFunctionRegexExtractID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PipelineFunctionRegexExtractID: %v", v)
	}
}

type PipelineFunctionRegexExtractConf struct {
	// Regex literal with named capturing groups, such as (?<foo>bar), or _NAME_ and _VALUE_ capturing groups, such as (?<_NAME_0>[^ =]+)=(?<_VALUE_0>[^,]+)
	Regex     string                             `json:"regex"`
	RegexList []ItemsTypeSerdeTypeRegexRegexList `json:"regexList,omitempty"`
	// Field on which to perform regex field extraction
	Source *string `json:"source,omitempty"`
	// The maximum number of times to apply regex to source field when the global flag is set, or when using _NAME_ and _VALUE_ capturing groups
	Iterations *float64 `json:"iterations,omitempty"`
	// JavaScript expression to format field names when _NAME_n and _VALUE_n capturing groups are used. Original field name is in global variable 'name'. Example: To append XX to all field names, use `${name}_XX` (backticks are literal). If empty, names will be sanitized using this regex: /^[_0-9]+|[^a-zA-Z0-9_]+/g. You can access other fields values via __e.<fieldName>.
	FieldNameExpression *string `json:"fieldNameExpression,omitempty"`
	// Overwrite existing event fields with extracted values. If disabled, existing fields will be converted to an array.
	Overwrite *bool `json:"overwrite,omitempty"`
}

func (p PipelineFunctionRegexExtractConf) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PipelineFunctionRegexExtractConf) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PipelineFunctionRegexExtractConf) GetRegex() string {
	if p == nil {
		return ""
	}
	return p.Regex
}

func (p *PipelineFunctionRegexExtractConf) GetRegexList() []ItemsTypeSerdeTypeRegexRegexList {
	if p == nil {
		return nil
	}
	return p.RegexList
}

func (p *PipelineFunctionRegexExtractConf) GetSource() *string {
	if p == nil {
		return nil
	}
	return p.Source
}

func (p *PipelineFunctionRegexExtractConf) GetIterations() *float64 {
	if p == nil {
		return nil
	}
	return p.Iterations
}

func (p *PipelineFunctionRegexExtractConf) GetFieldNameExpression() *string {
	if p == nil {
		return nil
	}
	return p.FieldNameExpression
}

func (p *PipelineFunctionRegexExtractConf) GetOverwrite() *bool {
	if p == nil {
		return nil
	}
	return p.Overwrite
}

type PipelineFunctionRegexExtract struct {
	// Filter that selects data to be fed through this Function
	Filter *string `json:"filter,omitempty"`
	// Function ID
	ID PipelineFunctionRegexExtractID `json:"id"`
	// Simple description of this step
	Description *string `json:"description,omitempty"`
	// If true, data will not be pushed through this function
	Disabled *bool `json:"disabled,omitempty"`
	// If enabled, stops the results of this Function from being passed to the downstream Functions
	Final *bool                            `json:"final,omitempty"`
	Conf  PipelineFunctionRegexExtractConf `json:"conf"`
	// Group ID
	GroupID *string `json:"groupId,omitempty"`
}

func (p PipelineFunctionRegexExtract) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PipelineFunctionRegexExtract) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PipelineFunctionRegexExtract) GetFilter() *string {
	if p == nil {
		return nil
	}
	return p.Filter
}

func (p *PipelineFunctionRegexExtract) GetID() PipelineFunctionRegexExtractID {
	if p == nil {
		return PipelineFunctionRegexExtractID("")
	}
	return p.ID
}

func (p *PipelineFunctionRegexExtract) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PipelineFunctionRegexExtract) GetDisabled() *bool {
	if p == nil {
		return nil
	}
	return p.Disabled
}

func (p *PipelineFunctionRegexExtract) GetFinal() *bool {
	if p == nil {
		return nil
	}
	return p.Final
}

func (p *PipelineFunctionRegexExtract) GetConf() PipelineFunctionRegexExtractConf {
	if p == nil {
		return PipelineFunctionRegexExtractConf{}
	}
	return p.Conf
}

func (p *PipelineFunctionRegexExtract) GetGroupID() *string {
	if p == nil {
		return nil
	}
	return p.GroupID
}
