// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RestartResponseStatus string

const (
	RestartResponseStatusError      RestartResponseStatus = "Error"
	RestartResponseStatusRestarting RestartResponseStatus = "Restarting"
)

func (e RestartResponseStatus) ToPointer() *RestartResponseStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RestartResponseStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "Error", "Restarting":
			return true
		}
	}
	return false
}

type RestartResponse struct {
	ID      string                `json:"id"`
	Message *string               `json:"message,omitempty"`
	Status  RestartResponseStatus `json:"status"`
}

func (r *RestartResponse) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RestartResponse) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *RestartResponse) GetStatus() RestartResponseStatus {
	if r == nil {
		return RestartResponseStatus("")
	}
	return r.Status
}
