// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RouteConf struct {
	Clones                 []map[string]string `json:"clones,omitempty"`
	Context                *string             `json:"context,omitempty"`
	Description            *string             `json:"description,omitempty"`
	Disabled               *bool               `json:"disabled,omitempty"`
	EnableOutputExpression *bool               `json:"enableOutputExpression,omitempty"`
	Filter                 *string             `json:"filter,omitempty"`
	Final                  bool                `json:"final"`
	GroupID                *string             `json:"groupId,omitempty"`
	ID                     string              `json:"id"`
	Name                   string              `json:"name"`
	Output                 *string             `json:"output,omitempty"`
	OutputExpression       *string             `json:"outputExpression,omitempty"`
	Pipeline               string              `json:"pipeline"`
	ToGroupContext         *bool               `json:"toGroupContext,omitempty"`
}

func (r *RouteConf) GetClones() []map[string]string {
	if r == nil {
		return nil
	}
	return r.Clones
}

func (r *RouteConf) GetContext() *string {
	if r == nil {
		return nil
	}
	return r.Context
}

func (r *RouteConf) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *RouteConf) GetDisabled() *bool {
	if r == nil {
		return nil
	}
	return r.Disabled
}

func (r *RouteConf) GetEnableOutputExpression() *bool {
	if r == nil {
		return nil
	}
	return r.EnableOutputExpression
}

func (r *RouteConf) GetFilter() *string {
	if r == nil {
		return nil
	}
	return r.Filter
}

func (r *RouteConf) GetFinal() bool {
	if r == nil {
		return false
	}
	return r.Final
}

func (r *RouteConf) GetGroupID() *string {
	if r == nil {
		return nil
	}
	return r.GroupID
}

func (r *RouteConf) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RouteConf) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RouteConf) GetOutput() *string {
	if r == nil {
		return nil
	}
	return r.Output
}

func (r *RouteConf) GetOutputExpression() *string {
	if r == nil {
		return nil
	}
	return r.OutputExpression
}

func (r *RouteConf) GetPipeline() string {
	if r == nil {
		return ""
	}
	return r.Pipeline
}

func (r *RouteConf) GetToGroupContext() *bool {
	if r == nil {
		return nil
	}
	return r.ToGroupContext
}
