// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

// PartitioningScheme - Partitioning scheme used for this dataset. Using a known scheme like DDSS enables more efficient data reading and retrieval.
type PartitioningScheme string

const (
	// PartitioningSchemeNone Defined in Path
	PartitioningSchemeNone PartitioningScheme = "none"
	// PartitioningSchemeDdss DDSS
	PartitioningSchemeDdss PartitioningScheme = "ddss"
)

func (e PartitioningScheme) ToPointer() *PartitioningScheme {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PartitioningScheme) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "ddss":
			return true
		}
	}
	return false
}

type S3CollectorConfExtractor struct {
	// A token from the template path, such as epoch
	Key string `json:"key"`
	// JavaScript expression that receives token under "value" variable, and evaluates to populate event fields. Example: {date: new Date(+value*1000)}
	Expression string `json:"expression"`
}

func (s S3CollectorConfExtractor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *S3CollectorConfExtractor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"key", "expression"}); err != nil {
		return err
	}
	return nil
}

func (s *S3CollectorConfExtractor) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

func (s *S3CollectorConfExtractor) GetExpression() string {
	if s == nil {
		return ""
	}
	return s.Expression
}

// S3CollectorConfAuthenticationMethod - AWS authentication method. Choose Auto to use IAM roles.
type S3CollectorConfAuthenticationMethod string

const (
	// S3CollectorConfAuthenticationMethodAuto Auto
	S3CollectorConfAuthenticationMethodAuto S3CollectorConfAuthenticationMethod = "auto"
	// S3CollectorConfAuthenticationMethodManual Manual
	S3CollectorConfAuthenticationMethodManual S3CollectorConfAuthenticationMethod = "manual"
	// S3CollectorConfAuthenticationMethodSecret Secret Key pair
	S3CollectorConfAuthenticationMethodSecret S3CollectorConfAuthenticationMethod = "secret"
)

func (e S3CollectorConfAuthenticationMethod) ToPointer() *S3CollectorConfAuthenticationMethod {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *S3CollectorConfAuthenticationMethod) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "manual", "secret":
			return true
		}
	}
	return false
}

// S3CollectorConfSignatureVersion - Signature version to use for signing S3 requests
type S3CollectorConfSignatureVersion string

const (
	S3CollectorConfSignatureVersionV2 S3CollectorConfSignatureVersion = "v2"
	S3CollectorConfSignatureVersionV4 S3CollectorConfSignatureVersion = "v4"
)

func (e S3CollectorConfSignatureVersion) ToPointer() *S3CollectorConfSignatureVersion {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *S3CollectorConfSignatureVersion) IsExact() bool {
	if e != nil {
		switch *e {
		case "v2", "v4":
			return true
		}
	}
	return false
}

type S3CollectorConf struct {
	// Name of the predefined Destination that will be used to auto-populate Collector settings
	OutputName *string `json:"outputName,omitempty"`
	// S3 Bucket from which to collect data
	Bucket string `json:"bucket"`
	// Maximum file size for each Parquet chunk
	ParquetChunkSizeMB *float64 `default:"5" json:"parquetChunkSizeMB"`
	// Maximum time allowed for downloading a Parquet chunk. Processing will stop if a chunk cannot be downloaded within the time specified.
	ParquetChunkDownloadTimeout *float64 `default:"600" json:"parquetChunkDownloadTimeout"`
	// Region from which to retrieve data
	Region *string `json:"region,omitempty"`
	// Directory where data will be collected. Templating (such as 'myDir/${datacenter}/${host}/${app}/') and time-based tokens (such as 'myOtherDir/${_time:%Y}/${_time:%m}/${_time:%d}/') are supported. Can be a constant (enclosed in quotes) or a JavaScript expression.
	Path *string `json:"path,omitempty"`
	// Partitioning scheme used for this dataset. Using a known scheme like DDSS enables more efficient data reading and retrieval.
	PartitioningScheme *PartitioningScheme `default:"none" json:"partitioningScheme"`
	// Allows using template tokens as context for expressions that enrich discovery results. For example, given a template /path/${epoch}, an extractor under key "epoch" with an expression {date: new Date(+value*1000)}, will enrich discovery results with a human readable "date" field.
	Extractors []S3CollectorConfExtractor `json:"extractors,omitempty"`
	// AWS authentication method. Choose Auto to use IAM roles.
	AwsAuthenticationMethod *S3CollectorConfAuthenticationMethod `default:"auto" json:"awsAuthenticationMethod"`
	// Must point to an S3-compatible endpoint. If empty, defaults to an AWS region-specific endpoint.
	Endpoint *string `json:"endpoint,omitempty"`
	// Signature version to use for signing S3 requests
	SignatureVersion *S3CollectorConfSignatureVersion `default:"v4" json:"signatureVersion"`
	// Use AssumeRole credentials
	EnableAssumeRole *bool `default:"false" json:"enableAssumeRole"`
	// Amazon Resource Name (ARN) of the role to assume
	AssumeRoleArn *string `json:"assumeRoleArn,omitempty"`
	// External ID to use when assuming role
	AssumeRoleExternalID *string `json:"assumeRoleExternalId,omitempty"`
	// Duration of the Assumed Role's session, in seconds. Minimum is 900 (15 minutes), default is 3600 (1 hour), and maximum is 43200 (12 hours).
	DurationSeconds *float64 `default:"3600" json:"durationSeconds"`
	// Maximum number of metadata objects to batch before recording as results
	MaxBatchSize *float64 `default:"10" json:"maxBatchSize"`
	Recurse      any      `json:"recurse,omitempty"`
	// Reuse connections between requests to improve performance
	ReuseConnections *bool `default:"true" json:"reuseConnections"`
	// Reject certificates that cannot be verified against a valid CA (such as a self-signed certificate)
	RejectUnauthorized *bool `default:"true" json:"rejectUnauthorized"`
	// Disable if you can access files within the bucket but not the bucket itself. Resolves errors of the form "discover task initialization failed...error: Forbidden".
	VerifyPermissions *bool `default:"true" json:"verifyPermissions"`
	// Disable Collector event time filtering when a date range is specified
	DisableTimeFilter *bool `default:"false" json:"disableTimeFilter"`
}

func (s S3CollectorConf) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *S3CollectorConf) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"bucket"}); err != nil {
		return err
	}
	return nil
}

func (s *S3CollectorConf) GetOutputName() *string {
	if s == nil {
		return nil
	}
	return s.OutputName
}

func (s *S3CollectorConf) GetBucket() string {
	if s == nil {
		return ""
	}
	return s.Bucket
}

func (s *S3CollectorConf) GetParquetChunkSizeMB() *float64 {
	if s == nil {
		return nil
	}
	return s.ParquetChunkSizeMB
}

func (s *S3CollectorConf) GetParquetChunkDownloadTimeout() *float64 {
	if s == nil {
		return nil
	}
	return s.ParquetChunkDownloadTimeout
}

func (s *S3CollectorConf) GetRegion() *string {
	if s == nil {
		return nil
	}
	return s.Region
}

func (s *S3CollectorConf) GetPath() *string {
	if s == nil {
		return nil
	}
	return s.Path
}

func (s *S3CollectorConf) GetPartitioningScheme() *PartitioningScheme {
	if s == nil {
		return nil
	}
	return s.PartitioningScheme
}

func (s *S3CollectorConf) GetExtractors() []S3CollectorConfExtractor {
	if s == nil {
		return nil
	}
	return s.Extractors
}

func (s *S3CollectorConf) GetAwsAuthenticationMethod() *S3CollectorConfAuthenticationMethod {
	if s == nil {
		return nil
	}
	return s.AwsAuthenticationMethod
}

func (s *S3CollectorConf) GetEndpoint() *string {
	if s == nil {
		return nil
	}
	return s.Endpoint
}

func (s *S3CollectorConf) GetSignatureVersion() *S3CollectorConfSignatureVersion {
	if s == nil {
		return nil
	}
	return s.SignatureVersion
}

func (s *S3CollectorConf) GetEnableAssumeRole() *bool {
	if s == nil {
		return nil
	}
	return s.EnableAssumeRole
}

func (s *S3CollectorConf) GetAssumeRoleArn() *string {
	if s == nil {
		return nil
	}
	return s.AssumeRoleArn
}

func (s *S3CollectorConf) GetAssumeRoleExternalID() *string {
	if s == nil {
		return nil
	}
	return s.AssumeRoleExternalID
}

func (s *S3CollectorConf) GetDurationSeconds() *float64 {
	if s == nil {
		return nil
	}
	return s.DurationSeconds
}

func (s *S3CollectorConf) GetMaxBatchSize() *float64 {
	if s == nil {
		return nil
	}
	return s.MaxBatchSize
}

func (s *S3CollectorConf) GetRecurse() any {
	if s == nil {
		return nil
	}
	return s.Recurse
}

func (s *S3CollectorConf) GetReuseConnections() *bool {
	if s == nil {
		return nil
	}
	return s.ReuseConnections
}

func (s *S3CollectorConf) GetRejectUnauthorized() *bool {
	if s == nil {
		return nil
	}
	return s.RejectUnauthorized
}

func (s *S3CollectorConf) GetVerifyPermissions() *bool {
	if s == nil {
		return nil
	}
	return s.VerifyPermissions
}

func (s *S3CollectorConf) GetDisableTimeFilter() *bool {
	if s == nil {
		return nil
	}
	return s.DisableTimeFilter
}
