// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// StorageClass1Options - Storage class to select for uploaded objects
type StorageClass1Options string

const (
	// StorageClass1OptionsStandard Standard Storage
	StorageClass1OptionsStandard StorageClass1Options = "STANDARD"
	// StorageClass1OptionsNearline Nearline Storage
	StorageClass1OptionsNearline StorageClass1Options = "NEARLINE"
	// StorageClass1OptionsColdline Coldline Storage
	StorageClass1OptionsColdline StorageClass1Options = "COLDLINE"
	// StorageClass1OptionsArchive Archive Storage
	StorageClass1OptionsArchive StorageClass1Options = "ARCHIVE"
)

func (e StorageClass1Options) ToPointer() *StorageClass1Options {
	return &e
}
