// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SystemTypeSystemSettingsConf struct {
	Intercom bool                                   `json:"intercom"`
	Upgrade  UpgradeOptionsSystemSettingsConfSystem `json:"upgrade"`
}

func (s *SystemTypeSystemSettingsConf) GetIntercom() bool {
	if s == nil {
		return false
	}
	return s.Intercom
}

func (s *SystemTypeSystemSettingsConf) GetUpgrade() UpgradeOptionsSystemSettingsConfSystem {
	if s == nil {
		return UpgradeOptionsSystemSettingsConfSystem("")
	}
	return s.Upgrade
}
