// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

// TaskErrorDetail - Task error details. May include a nested <code>reason</code> for wrapped errors and additional properties from the original error.
type TaskErrorDetail struct {
	// Human-readable error message.
	Message string `json:"message"`
	// Error name, if available.
	Name *string `json:"name,omitzero"`
	// Serialized error object that describes why a job entered its current <code>state</code>. Includes <code>message</code> and may include a nested <code>reason</code> for wrapped errors.
	Reason *TaskErrorInfo `json:"reason,omitzero"`
	// Truncated stack trace of the error.
	Stack *string `json:"stack,omitzero"`
}

func (t TaskErrorDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskErrorDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskErrorDetail) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

func (t *TaskErrorDetail) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TaskErrorDetail) GetReason() *TaskErrorInfo {
	if t == nil {
		return nil
	}
	return t.Reason
}

func (t *TaskErrorDetail) GetStack() *string {
	if t == nil {
		return nil
	}
	return t.Stack
}
