// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/criblio/cribl-control-plane-sdk-go/internal/utils"
)

type UpgradeGroupSettings2 struct {
}

func (u UpgradeGroupSettings2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpgradeGroupSettings2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

type UpgradeGroupSettings1 struct {
	IsRolling  *bool    `json:"isRolling,omitempty"`
	Quantity   *float64 `json:"quantity,omitempty"`
	RetryCount *float64 `json:"retryCount,omitempty"`
	RetryDelay *float64 `json:"retryDelay,omitempty"`
}

func (u UpgradeGroupSettings1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpgradeGroupSettings1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpgradeGroupSettings1) GetIsRolling() *bool {
	if u == nil {
		return nil
	}
	return u.IsRolling
}

func (u *UpgradeGroupSettings1) GetQuantity() *float64 {
	if u == nil {
		return nil
	}
	return u.Quantity
}

func (u *UpgradeGroupSettings1) GetRetryCount() *float64 {
	if u == nil {
		return nil
	}
	return u.RetryCount
}

func (u *UpgradeGroupSettings1) GetRetryDelay() *float64 {
	if u == nil {
		return nil
	}
	return u.RetryDelay
}

type UpgradeGroupSettingsUnionType string

const (
	UpgradeGroupSettingsUnionTypeUpgradeGroupSettings1 UpgradeGroupSettingsUnionType = "UpgradeGroupSettings_1"
	UpgradeGroupSettingsUnionTypeUpgradeGroupSettings2 UpgradeGroupSettingsUnionType = "UpgradeGroupSettings_2"
)

type UpgradeGroupSettingsUnion struct {
	UpgradeGroupSettings1 *UpgradeGroupSettings1 `queryParam:"inline,name=UpgradeGroupSettings" union:"member"`
	UpgradeGroupSettings2 *UpgradeGroupSettings2 `queryParam:"inline,name=UpgradeGroupSettings" union:"member"`

	Type UpgradeGroupSettingsUnionType
}

func CreateUpgradeGroupSettingsUnionUpgradeGroupSettings1(upgradeGroupSettings1 UpgradeGroupSettings1) UpgradeGroupSettingsUnion {
	typ := UpgradeGroupSettingsUnionTypeUpgradeGroupSettings1

	return UpgradeGroupSettingsUnion{
		UpgradeGroupSettings1: &upgradeGroupSettings1,
		Type:                  typ,
	}
}

func CreateUpgradeGroupSettingsUnionUpgradeGroupSettings2(upgradeGroupSettings2 UpgradeGroupSettings2) UpgradeGroupSettingsUnion {
	typ := UpgradeGroupSettingsUnionTypeUpgradeGroupSettings2

	return UpgradeGroupSettingsUnion{
		UpgradeGroupSettings2: &upgradeGroupSettings2,
		Type:                  typ,
	}
}

func (u *UpgradeGroupSettingsUnion) UnmarshalJSON(data []byte) error {

	var upgradeGroupSettings1 UpgradeGroupSettings1 = UpgradeGroupSettings1{}
	if err := utils.UnmarshalJSON(data, &upgradeGroupSettings1, "", true, nil); err == nil {
		u.UpgradeGroupSettings1 = &upgradeGroupSettings1
		u.Type = UpgradeGroupSettingsUnionTypeUpgradeGroupSettings1
		return nil
	}

	var upgradeGroupSettings2 UpgradeGroupSettings2 = UpgradeGroupSettings2{}
	if err := utils.UnmarshalJSON(data, &upgradeGroupSettings2, "", true, nil); err == nil {
		u.UpgradeGroupSettings2 = &upgradeGroupSettings2
		u.Type = UpgradeGroupSettingsUnionTypeUpgradeGroupSettings2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpgradeGroupSettingsUnion", string(data))
}

func (u UpgradeGroupSettingsUnion) MarshalJSON() ([]byte, error) {
	if u.UpgradeGroupSettings1 != nil {
		return utils.MarshalJSON(u.UpgradeGroupSettings1, "", true)
	}

	if u.UpgradeGroupSettings2 != nil {
		return utils.MarshalJSON(u.UpgradeGroupSettings2, "", true)
	}

	return nil, errors.New("could not marshal union type UpgradeGroupSettingsUnion: all fields are null")
}
