// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/criblio/cribl-control-plane-sdk-go/models/components"
)

type HealthServerStatusError struct {
	Role      *components.Role                    `json:"role,omitzero"`
	StartTime float64                             `json:"startTime"`
	Status    components.HealthServerStatusStatus `json:"status"`
	HTTPMeta  components.HTTPMetadata             `json:"-"`
}

var _ error = &HealthServerStatusError{}

func (e *HealthServerStatusError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
