workflowVersion: 1.0.0
speakeasyVersion: 1.639.3
sources:
    Cribl API Reference:
        inputs:
            - location: https://raw.githubusercontent.com/criblio/cribl-openapi-spec/main/specs/control-plane-dev.yml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/cribl/cribl/cribl-api-reference
targets:
    cribl-control-plane:
        target: go
        source: Cribl API Reference
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cribl/cribl/cribl-api-reference-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
        testing:
            enabled: false
